import { Destination } from "./types";

const img = (seed: string, w = 1200, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const delhi: Destination = {
  slug: "delhi",
  name: "Delhi",
  tagline: "City of Seven Cities",
  region: "National Capital Territory",
  country: "India",
  rating: 4.6,
  heroImage: img("delhi-hero", 1800, 1100),
  cardImage: img("delhi-card", 900, 1100),
  tags: ["Heritage", "Food", "Culture"],
  bestTime: "Oct – Mar",
  center: { lat: 28.6139, lng: 77.209 },
  quickFacts: { weather: "28°C", budget: "₹₹", language: "Hindi", stay: "3–4 Days" },
  intro:
    "Delhi has been rebuilt as a capital at least seven times over a thousand years, and it shows — Mughal domes sit a few kilometres from British colonnades, which sit a few kilometres from glass office towers. It's less a single city than several cities stacked on top of each other, each one still half-alive in the next.",
  didYouKnow: [
    "Delhi has been the capital of at least seven historical empires, from the Tomars to the British Raj.",
    "The Red Fort was the residence of Mughal emperors for nearly 200 years.",
    "Connaught Place was designed by British architects to resemble Bath, England.",
    "Delhi's Qutub Minar is the tallest brick minaret in the world, at 73 metres.",
    "The city has more Mughal-era monuments than any other in India, including three UNESCO World Heritage Sites.",
  ],
  attractions: [
    {
      slug: "red-fort",
      name: "Red Fort",
      category: "Historical",
      rating: 4.6,
      image: img("red-fort", 1200, 900),
      duration: "2 hours",
      ticket: "₹35 (Indians) / ₹550 (Foreigners)",
      hours: "9:30 AM – 4:30 PM (closed Mondays)",
      bestTime: "Morning, before the crowds",
      about:
        "Built by Shah Jahan as the seat of Mughal power, the Red Fort's massive red sandstone walls once enclosed a self-contained city of palaces, gardens and marketplaces. It's from its ramparts that India's Prime Minister addresses the nation every Independence Day.",
      architecture:
        "Mughal fort architecture in red sandstone, blending Persian, Timurid and Hindu traditions, with the Diwan-i-Khas known for its marble inlay work.",
      location: "Netaji Subhash Marg, Old Delhi",
      lat: 28.6562,
      lng: 77.241,
    },
    {
      slug: "humayuns-tomb",
      name: "Humayun's Tomb",
      category: "Heritage",
      rating: 4.7,
      image: img("humayun-tomb", 1200, 900),
      duration: "1.5 hours",
      ticket: "₹35 (Indians) / ₹550 (Foreigners)",
      hours: "6:00 AM – 6:00 PM",
      bestTime: "Late afternoon",
      about:
        "Commissioned by Humayun's widow in 1570, this garden tomb was the first of its kind in India and the architectural template later refined into the Taj Mahal. Set within a formal Persian charbagh garden, it's often called the Taj's elder sibling.",
      architecture:
        "Early Mughal architecture in red sandstone with white and black marble inlay, built on a raised platform within a symmetrical char-bagh garden.",
      location: "Mathura Road, Nizamuddin",
      lat: 28.5933,
      lng: 77.2507,
    },
    {
      slug: "qutub-minar",
      name: "Qutub Minar",
      category: "Historical",
      rating: 4.6,
      image: img("qutub-minar", 1200, 900),
      duration: "1–1.5 hours",
      ticket: "₹35 (Indians) / ₹550 (Foreigners)",
      hours: "7:00 AM – 5:00 PM",
      bestTime: "Early morning",
      about:
        "The tallest brick minaret in the world, started in 1192 to mark the beginning of Muslim rule in India. The complex around it includes the Iron Pillar, over 1,600 years old and famously rust-resistant.",
      architecture:
        "Indo-Islamic architecture, five storeys tapering upward, built in red sandstone and marble with intricate Quranic inscriptions.",
      location: "Mehrauli, South Delhi",
      lat: 28.5245,
      lng: 77.1855,
    },
    {
      slug: "india-gate",
      name: "India Gate",
      category: "Landmark",
      rating: 4.5,
      image: img("india-gate", 1200, 900),
      duration: "45 minutes",
      ticket: "Free",
      hours: "Open 24 hours",
      bestTime: "Evening, when it's lit up",
      about:
        "A 42-metre war memorial commemorating over 70,000 Indian soldiers who died in World War I, its arch inscribed with their names. The surrounding lawns are one of Delhi's most popular evening gathering spots.",
      architecture:
        "Designed by Edwin Lutyens in the style of a triumphal arch, drawing on Roman and Indian architectural influences.",
      location: "Rajpath, New Delhi",
      lat: 28.6129,
      lng: 77.2295,
    },
  ],
  history: [
    {
      year: "1206",
      title: "Delhi Sultanate begins",
      description:
        "Qutub-ud-din Aibak establishes the Delhi Sultanate, beginning centuries of Islamic rule and the construction of the Qutub Minar.",
    },
    {
      year: "1638",
      title: "Shahjahanabad founded",
      description:
        "Shah Jahan moves the Mughal capital to Delhi, building the Red Fort and the walled city now known as Old Delhi.",
    },
    {
      year: "1911",
      title: "New Delhi designed",
      description:
        "The British shift their colonial capital from Calcutta to Delhi, commissioning Edwin Lutyens to design an entirely new imperial city.",
    },
    {
      year: "1947",
      title: "Capital of independent India",
      description:
        "Delhi becomes the capital of a newly independent India, and the site of Jawaharlal Nehru's midnight address to the nation.",
    },
  ],
  culture: [
    {
      slug: "qawwali",
      title: "Qawwali at Nizamuddin",
      category: "Music",
      image: img("qawwali", 900, 1100),
      description:
        "Devotional Sufi singing performed live every Thursday evening at the shrine of Nizamuddin Auliya, a tradition unbroken for over 700 years.",
    },
    {
      slug: "chandni-chowk",
      title: "Chandni Chowk",
      category: "Marketplace",
      image: img("chandni-chowk", 900, 1100),
      description:
        "A 17th-century market built by Shah Jahan's daughter, still one of India's busiest wholesale and street food districts.",
    },
    {
      slug: "delhi-durbar-cuisine",
      title: "Mughlai Cuisine",
      category: "Tradition",
      image: img("mughlai-cuisine", 900, 1100),
      description:
        "Rich, slow-cooked court cuisine developed under the Mughals — kebabs, biryanis and korma still cooked the same way in Old Delhi's oldest kitchens.",
    },
  ],
  food: [
    {
      slug: "butter-chicken",
      name: "Butter Chicken",
      origin: "Invented in Delhi, 1950s",
      image: img("butter-chicken", 1000, 800),
      description:
        "Tandoori chicken simmered in a creamy tomato gravy, invented at Moti Mahal restaurant as a way to use up leftover tandoori chicken by cooking it in butter and tomato.",
      ingredients: ["Chicken", "Tomato", "Butter", "Cream", "Garam masala"],
      taste: "Rich, mildly spiced and buttery",
      significance: "Now one of India's most internationally recognised dishes.",
      whereToTry: "Moti Mahal, Daryaganj",
    },
    {
      slug: "chaat",
      name: "Delhi Chaat",
      origin: "North Indian street food",
      image: img("chaat", 1000, 800),
      description:
        "A category more than a single dish — golgappa, aloo tikki and papdi chaat sold from carts across the city, layered with tangy tamarind and mint chutneys.",
      ingredients: ["Potato", "Chickpeas", "Tamarind chutney", "Yogurt", "Sev"],
      taste: "Tangy, spicy and crunchy all at once",
      significance: "A daily ritual for Delhiites, eaten standing at the cart.",
      whereToTry: "Bengali Market, Chandni Chowk",
    },
    {
      slug: "paranthe",
      name: "Stuffed Paranthas",
      origin: "Paranthe Wali Gali, Old Delhi",
      image: img("parantha", 1000, 800),
      description:
        "Deep-fried, stuffed flatbreads served with pickles and yogurt, sold on a single Old Delhi lane that's specialised in them for over a century.",
      ingredients: ["Wheat flour", "Potato or paneer filling", "Ghee", "Pickles"],
      taste: "Crisp outside, richly stuffed inside",
      significance: "Paranthe Wali Gali has served the same recipe since the 1870s.",
      whereToTry: "Paranthe Wali Gali, Chandni Chowk",
    },
  ],
  gallery: [
    { image: img("delhi-g1", 900, 1200), category: "Heritage", caption: "Red Fort ramparts at dusk", tall: true },
    { image: img("delhi-g2", 1200, 900), category: "Street", caption: "Chandni Chowk in the evening" },
    { image: img("delhi-g3", 900, 1200), category: "Heritage", caption: "Humayun's Tomb gardens", tall: true },
    { image: img("delhi-g4", 1200, 900), category: "Food", caption: "Street chaat vendor" },
    { image: img("delhi-g5", 900, 1200), category: "Landmark", caption: "India Gate at night", tall: true },
    { image: img("delhi-g6", 1200, 900), category: "Heritage", caption: "Qutub Minar" },
  ],
  hotels: [
    { slug: "the-imperial", name: "The Imperial", tier: "Luxury", pricePerNight: 18000, rating: 4.8, image: img("delhi-hotel-1", 900, 700), lat: 28.6259, lng: 77.219 },
    { slug: "bloomrooms-new-delhi", name: "bloomrooms @ New Delhi Railway Station", tier: "Mid-range", pricePerNight: 4200, rating: 4.3, image: img("delhi-hotel-2", 900, 700), lat: 28.6425, lng: 77.2197 },
    { slug: "zostel-delhi", name: "Zostel Delhi", tier: "Budget", pricePerNight: 900, rating: 4.2, image: img("delhi-hotel-3", 900, 700), lat: 28.6304, lng: 77.2177 },
  ],
  restaurants: [
    { slug: "karims", name: "Karim's", cuisine: "Mughlai", priceLevel: 2, rating: 4.5, image: img("delhi-resto-1", 900, 700), lat: 28.6507, lng: 77.2334 },
    { slug: "indian-accent", name: "Indian Accent", cuisine: "Modern Indian", priceLevel: 4, rating: 4.7, image: img("delhi-resto-2", 900, 700), lat: 28.5988, lng: 77.1855 },
    { slug: "sagar-ratna", name: "Sagar Ratna", cuisine: "South Indian", priceLevel: 2, rating: 4.3, image: img("delhi-resto-3", 900, 700), lat: 28.5645, lng: 77.203 },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["English", "Punjabi", "Urdu"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nuh-mas-tay" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhun-ya-vaad" },
      { phrase: "Kitna hai?", translation: "How much is it?", phonetic: "kit-na hai" },
      { phrase: "Yeh kahan hai?", translation: "Where is this?", phonetic: "yeh kuh-haan hai" },
    ],
  },
  transport: [
    { mode: "Flight", from: "Any major city", approxTime: "Varies", approxCost: "₹3,000–₹10,000", detail: "Indira Gandhi International Airport (DEL) is India's busiest airport." },
    { mode: "Train", from: "Mumbai", approxTime: "16 hours", approxCost: "₹800–₹3,500", detail: "Rajdhani Express services run overnight from most metros." },
    { mode: "Car", from: "Agra", approxTime: "3.5 hours", approxCost: "₹2,500–₹4,000", detail: "Via the Yamuna Expressway." },
  ],
  weather: {
    tempC: 28,
    feelsLikeC: 30,
    humidity: 45,
    windKmh: 12,
    condition: "Sunny",
    forecast: [
      { label: "Mon", tempC: 28, condition: "Sunny" },
      { label: "Tue", tempC: 27, condition: "Partly Cloudy" },
      { label: "Wed", tempC: 29, condition: "Sunny" },
      { label: "Thu", tempC: 26, condition: "Cloudy" },
      { label: "Fri", tempC: 28, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Cool and pleasant, occasional fog" },
    { month: "Feb", score: 2, note: "Mild and sunny" },
    { month: "Mar", score: 1, note: "Warming up quickly" },
    { month: "Apr", score: 0, note: "Getting hot" },
    { month: "May", score: 0, note: "Peak heat, avoid" },
    { month: "Jun", score: 0, note: "Very hot, monsoon starts late" },
    { month: "Jul", score: 1, note: "Monsoon, humid but green" },
    { month: "Aug", score: 1, note: "Monsoon continues" },
    { month: "Sep", score: 1, note: "Monsoon tapering off" },
    { month: "Oct", score: 2, note: "Pleasant and festive" },
    { month: "Nov", score: 2, note: "Cool and clear" },
    { month: "Dec", score: 2, note: "Cool, best for sightseeing" },
  ],
  festivals: [
    { slug: "diwali-delhi", name: "Diwali", dateLabel: "Oct/Nov", image: img("delhi-diwali", 900, 700), description: "The festival of lights transforms the whole city with lamps, fireworks and markets." },
    { slug: "republic-day", name: "Republic Day Parade", dateLabel: "26 January", image: img("delhi-republic-day", 900, 700), description: "A grand military and cultural parade down Rajpath, celebrating India's constitution." },
  ],
  shopping: [
    { category: "Textiles", item: "Chikankari embroidery", image: img("delhi-shop-1", 900, 700), priceRange: "₹800–₹8,000", whereToBuy: "Karol Bagh, Cottage Emporium", bargainingTip: "Check stitch density — finer work costs more but lasts longer." },
    { category: "Spices", item: "Mixed spice boxes", image: img("delhi-shop-2", 900, 700), priceRange: "₹200–₹1,500", whereToBuy: "Khari Baoli spice market", bargainingTip: "Buy from stalls with visible turnover for freshness." },
    { category: "Books", item: "Secondhand & rare books", image: img("delhi-shop-3", 900, 700), priceRange: "₹50–₹2,000", whereToBuy: "Daryaganj Sunday book market", bargainingTip: "Arrive early on Sunday for the best finds." },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Use registered taxis or ride-hailing apps rather than unmarked cabs.",
      "Old Delhi's lanes are dense and easy to get lost in — keep a map handy.",
      "Avoid isolated areas late at night, especially for solo travellers.",
      "Bargain firmly but politely in markets — first quoted prices are rarely final.",
      "Stay hydrated and carry sunscreen in summer months.",
    ],
  },
};

export const agra: Destination = {
  slug: "agra",
  name: "Agra",
  tagline: "Home of the Taj Mahal",
  region: "Uttar Pradesh",
  country: "India",
  rating: 4.7,
  heroImage: img("agra-hero", 1800, 1100),
  cardImage: img("agra-card", 900, 1100),
  tags: ["Heritage", "Architecture", "Romance"],
  bestTime: "Oct – Mar",
  center: { lat: 27.1767, lng: 78.0081 },
  quickFacts: { weather: "30°C", budget: "₹₹", language: "Hindi", stay: "1–2 Days" },
  intro:
    "Agra exists, in the popular imagination, as the frame around a single building — but the Mughal capital that produced the Taj Mahal left behind an entire city of red sandstone forts and marble tombs, most of them nearly empty of the crowds that queue for its most famous monument.",
  didYouKnow: [
    "The Taj Mahal took approximately 22 years and 20,000 workers to build.",
    "It's said Shah Jahan planned a black marble mausoleum for himself across the river — never built.",
    "Agra Fort was the primary residence of Mughal emperors until 1638.",
    "The Taj Mahal changes colour throughout the day, from pinkish at dawn to golden at sunset.",
  ],
  attractions: [
    {
      slug: "taj-mahal",
      name: "Taj Mahal",
      category: "Historical",
      rating: 4.9,
      image: img("taj-mahal", 1200, 900),
      duration: "2–3 hours",
      ticket: "₹50 (Indians) / ₹1,300 (Foreigners)",
      hours: "Sunrise to sunset (closed Fridays)",
      bestTime: "Sunrise, for the light and smaller crowds",
      about:
        "Built by Shah Jahan as a mausoleum for his wife Mumtaz Mahal, the Taj Mahal is widely considered the finest example of Mughal architecture — a perfectly symmetrical white marble monument to grief and love, inlaid with semi-precious stones.",
      architecture:
        "Mughal architecture at its peak: white marble inlaid with precious and semi-precious stones (pietra dura), a central dome flanked by four minarets, set within a formal charbagh garden.",
      location: "Dharmapuri, Forest Colony, Agra",
      lat: 27.1751,
      lng: 78.0421,
    },
    {
      slug: "agra-fort",
      name: "Agra Fort",
      category: "Historical",
      rating: 4.6,
      image: img("agra-fort", 1200, 900),
      duration: "1.5–2 hours",
      ticket: "₹40 (Indians) / ₹550 (Foreigners)",
      hours: "6:00 AM – 6:00 PM",
      bestTime: "Late afternoon, for Taj Mahal views from the ramparts",
      about:
        "A red sandstone fortress-palace that served as the main residence of Mughal emperors before the capital moved to Delhi. Shah Jahan was imprisoned here by his son Aurangzeb, spending his final years gazing at the Taj Mahal from a balcony.",
      architecture:
        "A blend of Hindu and Islamic architectural styles in red sandstone, later additions in white marble by Shah Jahan.",
      location: "Rakabganj, Agra",
      lat: 27.1795,
      lng: 78.0211,
    },
    {
      slug: "fatehpur-sikri",
      name: "Fatehpur Sikri",
      category: "Heritage",
      rating: 4.6,
      image: img("fatehpur-sikri", 1200, 900),
      duration: "2–3 hours",
      ticket: "₹35 (Indians) / ₹550 (Foreigners)",
      hours: "6:00 AM – 6:00 PM",
      bestTime: "Morning, to beat the heat",
      about:
        "A fully preserved Mughal capital city, built by Akbar in 1571 and abandoned just 15 years later due to water shortages. Its palaces, courts and mosque sit exactly as they did nearly 450 years ago.",
      architecture:
        "Red sandstone Mughal architecture combining Persian, Hindu and Islamic elements, notably the Buland Darwaza — one of the tallest gateways in the world.",
      location: "40 km from Agra city",
      lat: 27.0945,
      lng: 77.6679,
    },
  ],
  history: [
    { year: "1526", title: "Mughal rule begins", description: "Babur defeats the Lodi dynasty at the First Battle of Panipat, beginning Mughal rule with Agra as an early capital." },
    { year: "1565", title: "Agra Fort rebuilt", description: "Akbar rebuilds Agra Fort in red sandstone, making it the primary Mughal seat of power." },
    { year: "1632–1653", title: "The Taj Mahal is built", description: "Shah Jahan commissions the Taj Mahal in memory of his wife Mumtaz Mahal, who died in childbirth." },
    { year: "1983", title: "UNESCO recognition", description: "The Taj Mahal is designated a UNESCO World Heritage Site, cited as 'the jewel of Muslim art in India'." },
  ],
  culture: [
    { slug: "marble-inlay", title: "Marble Pietra Dura", category: "Handicraft", image: img("agra-marble", 900, 1100), description: "The same stone-inlay technique used on the Taj Mahal is still practised by artisan families in Agra, passed down for generations." },
    { slug: "mughal-gardens", title: "Charbagh Gardens", category: "Tradition", image: img("agra-garden", 900, 1100), description: "The formal four-quadrant Persian garden style seen at the Taj Mahal and Fatehpur Sikri, symbolising the four rivers of paradise." },
    { slug: "agra-leather", title: "Leather Craft", category: "Handicraft", image: img("agra-leather", 900, 1100), description: "Agra has a centuries-old leatherworking tradition, producing shoes and goods sold across its markets today." },
  ],
  food: [
    {
      slug: "petha",
      name: "Agra Petha",
      origin: "Agra sweet shops",
      image: img("petha", 1000, 800),
      description: "A translucent, sugar-syrup-soaked sweet made from ash gourd, Agra's signature confection sold in dozens of flavours.",
      ingredients: ["Ash gourd", "Sugar syrup", "Lime", "Flavouring (rose, saffron)"],
      taste: "Sweet, chewy and syrupy",
      significance: "A Mughal-era recipe, now Agra's most famous export.",
      whereToTry: "Panchhi Petha, Sadar Bazaar",
    },
    {
      slug: "mughlai-paratha",
      name: "Mughlai Paratha",
      origin: "Mughal court kitchens",
      image: img("mughlai-paratha", 1000, 800),
      description: "A layered flatbread stuffed with minced meat and egg, fried until crisp — a rich, filling Mughlai classic.",
      ingredients: ["Wheat flour", "Minced meat", "Egg", "Onion", "Spices"],
      taste: "Crisp, savoury and rich",
      significance: "A staple of Agra's Mughlai food culture.",
      whereToTry: "Sadar Bazaar food stalls",
    },
    {
      slug: "bedai",
      name: "Bedai & Jalebi",
      origin: "Agra breakfast tradition",
      image: img("bedai", 1000, 800),
      description: "A deep-fried, lentil-stuffed puri served with spicy potato curry, paired with syrupy jalebi — Agra's classic breakfast combo.",
      ingredients: ["Wheat flour", "Urad dal", "Potato", "Sugar syrup"],
      taste: "Savoury and sweet together",
      significance: "A morning ritual across Agra's old city.",
      whereToTry: "Deviram Sweets, Rawatpara",
    },
  ],
  gallery: [
    { image: img("agra-g1", 900, 1200), category: "Landmark", caption: "Taj Mahal at sunrise", tall: true },
    { image: img("agra-g2", 1200, 900), category: "Heritage", caption: "Agra Fort ramparts" },
    { image: img("agra-g3", 900, 1200), category: "Heritage", caption: "Fatehpur Sikri courtyard", tall: true },
    { image: img("agra-g4", 1200, 900), category: "Detail", caption: "Marble inlay close-up" },
    { image: img("agra-g5", 900, 1200), category: "Food", caption: "Agra petha stall", tall: true },
  ],
  hotels: [
    { slug: "oberoi-amarvilas", name: "The Oberoi Amarvilas", tier: "Luxury", pricePerNight: 45000, rating: 4.9, image: img("agra-hotel-1", 900, 700), lat: 27.1721, lng: 78.0421 },
    { slug: "howard-plaza-agra", name: "Howard Plaza Taj Highway", tier: "Mid-range", pricePerNight: 3800, rating: 4.2, image: img("agra-hotel-2", 900, 700), lat: 27.16, lng: 78.03 },
    { slug: "zostel-agra", name: "Zostel Agra", tier: "Budget", pricePerNight: 700, rating: 4.1, image: img("agra-hotel-3", 900, 700), lat: 27.174, lng: 78.02 },
  ],
  restaurants: [
    { slug: "pinch-of-spice", name: "Pinch of Spice", cuisine: "North Indian", priceLevel: 2, rating: 4.4, image: img("agra-resto-1", 900, 700), lat: 27.1636, lng: 78.0176 },
    { slug: "esphahan", name: "Esphahan", cuisine: "Mughlai Fine Dining", priceLevel: 4, rating: 4.7, image: img("agra-resto-2", 900, 700), lat: 27.1721, lng: 78.0421 },
    { slug: "dasaprakash", name: "Dasaprakash", cuisine: "South Indian", priceLevel: 2, rating: 4.2, image: img("agra-resto-3", 900, 700), lat: 27.1995, lng: 78.0077 },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["English", "Urdu"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nuh-mas-tay" },
      { phrase: "Kitna paisa?", translation: "How much money?", phonetic: "kit-na pai-sa" },
      { phrase: "Bahut sundar hai", translation: "It's very beautiful", phonetic: "ba-hut sun-dar hai" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhun-ya-vaad" },
    ],
  },
  transport: [
    { mode: "Train", from: "Delhi", approxTime: "2 hours", approxCost: "₹500–₹1,500", detail: "Gatimaan Express is India's fastest train, running Delhi–Agra." },
    { mode: "Car", from: "Delhi", approxTime: "3.5 hours", approxCost: "₹2,500–₹4,000", detail: "Via the Yamuna Expressway." },
    { mode: "Flight", from: "Mumbai", approxTime: "1.5 hours", approxCost: "₹4,000–₹9,000", detail: "Agra Airport has limited but growing connectivity." },
  ],
  weather: {
    tempC: 30,
    feelsLikeC: 32,
    humidity: 40,
    windKmh: 10,
    condition: "Sunny",
    forecast: [
      { label: "Mon", tempC: 30, condition: "Sunny" },
      { label: "Tue", tempC: 29, condition: "Sunny" },
      { label: "Wed", tempC: 31, condition: "Partly Cloudy" },
      { label: "Thu", tempC: 28, condition: "Cloudy" },
      { label: "Fri", tempC: 30, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Cool, occasional morning fog" },
    { month: "Feb", score: 2, note: "Pleasant and clear" },
    { month: "Mar", score: 1, note: "Warming up" },
    { month: "Apr", score: 0, note: "Getting hot" },
    { month: "May", score: 0, note: "Peak heat, avoid" },
    { month: "Jun", score: 0, note: "Very hot" },
    { month: "Jul", score: 1, note: "Monsoon relief" },
    { month: "Aug", score: 1, note: "Monsoon continues" },
    { month: "Sep", score: 1, note: "Humid, tapering monsoon" },
    { month: "Oct", score: 2, note: "Clear and pleasant" },
    { month: "Nov", score: 2, note: "Ideal sightseeing weather" },
    { month: "Dec", score: 2, note: "Cool, best for photos" },
  ],
  festivals: [
    { slug: "taj-mahotsav", name: "Taj Mahotsav", dateLabel: "18–27 February", image: img("agra-mahotsav", 900, 700), description: "A ten-day festival of Mughal-era arts, crafts, music and cuisine held near the Taj Mahal." },
    { slug: "agra-diwali", name: "Diwali", dateLabel: "Oct/Nov", image: img("agra-diwali", 900, 700), description: "Agra's markets and monuments light up for the festival of lights." },
  ],
  shopping: [
    { category: "Handicrafts", item: "Marble inlay (pietra dura)", image: img("agra-shop-1", 900, 700), priceRange: "₹500–₹20,000", whereToBuy: "Sadar Bazaar, government emporiums", bargainingTip: "Genuine inlay uses real stone, not paint — check that colour doesn't scratch off." },
    { category: "Sweets", item: "Petha", image: img("agra-shop-2", 900, 700), priceRange: "₹150–₹500/kg", whereToBuy: "Panchhi Petha outlets citywide", bargainingTip: "Prices are largely fixed at established shops — quality varies more than price." },
    { category: "Leather", item: "Leather shoes & bags", image: img("agra-shop-3", 900, 700), priceRange: "₹500–₹4,000", whereToBuy: "Sadar Bazaar", bargainingTip: "Check stitching quality closely before settling on a price." },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Book Taj Mahal tickets online in advance to skip queues.",
      "Use only authorised guides inside the Taj Mahal complex.",
      "Beware of touts offering 'skip the line' services outside official ticket counters.",
      "Carry water and sun protection — little shade inside the monument complexes.",
      "Agree on auto-rickshaw fares before starting the ride.",
    ],
  },
};

export const udaipur: Destination = {
  slug: "udaipur",
  name: "Udaipur",
  tagline: "City of Lakes",
  region: "Rajasthan",
  country: "India",
  rating: 4.8,
  heroImage: img("udaipur-hero", 1800, 1100),
  cardImage: img("udaipur-card", 900, 1100),
  tags: ["Romance", "Heritage", "Lakes"],
  bestTime: "Sep – Mar",
  center: { lat: 24.5854, lng: 73.7125 },
  quickFacts: { weather: "27°C", budget: "₹₹", language: "Hindi", stay: "2–3 Days" },
  intro:
    "Udaipur is what happens when a desert kingdom decides to build around water instead of against it. Marble palaces rise straight out of artificial lakes, ringed by the Aravalli hills, in a city so consistently cinematic that half of Bollywood — and a fair chunk of Hollywood, including a Bond film — has shot here.",
  didYouKnow: [
    "Udaipur is called the 'Venice of the East' for its network of artificial lakes.",
    "The James Bond film Octopussy was partly filmed at Lake Palace and Monsoon Palace.",
    "City Palace is actually a complex of 11 palaces built over nearly 400 years.",
    "Lake Pichola was created in 1362, predating the city itself by two centuries.",
  ],
  attractions: [
    {
      slug: "city-palace-udaipur",
      name: "City Palace",
      category: "Heritage",
      rating: 4.8,
      image: img("udaipur-city-palace", 1200, 900),
      duration: "2–3 hours",
      ticket: "₹300 (Indians) / ₹700 (Foreigners)",
      hours: "9:30 AM – 5:30 PM",
      bestTime: "Morning light for photography",
      about:
        "The largest palace complex in Rajasthan, built and expanded by successive Mewar maharanas over nearly four centuries on the eastern shore of Lake Pichola. Its balconies, towers and cupolas offer sweeping views across the lake to the Aravalli hills.",
      architecture:
        "A fusion of Rajasthani, Mughal, Medieval, European and Chinese architectural styles, built primarily in granite and marble.",
      location: "Old City, Udaipur",
      lat: 24.5764,
      lng: 73.6835,
    },
    {
      slug: "lake-pichola",
      name: "Lake Pichola",
      category: "Landmark",
      rating: 4.8,
      image: img("lake-pichola", 1200, 900),
      duration: "1–2 hours (boat ride)",
      ticket: "₹700 for boat ride (approx.)",
      hours: "10:00 AM – 6:00 PM",
      bestTime: "Sunset boat ride",
      about:
        "An artificial lake built in 1362, home to the floating Lake Palace and Jag Mandir island. A sunset boat ride here, watching the City Palace glow gold against the water, is Udaipur's signature experience.",
      architecture:
        "N/A — the lake itself, though it frames the marble Lake Palace and Jag Mandir.",
      location: "Central Udaipur",
      lat: 24.5764,
      lng: 73.6808,
    },
    {
      slug: "jagdish-temple",
      name: "Jagdish Temple",
      category: "Religious",
      rating: 4.6,
      image: img("jagdish-temple", 1200, 900),
      duration: "45 minutes",
      ticket: "Free",
      hours: "5:00 AM – 2:00 PM, 4:00 PM – 10:00 PM",
      bestTime: "Evening aarti",
      about:
        "A grand Indo-Aryan temple built in 1651, dedicated to Lord Vishnu, just steps from the City Palace. Its intricately carved shikhara tower rises 79 feet above the old city streets.",
      architecture:
        "Indo-Aryan temple architecture with elaborately carved pillars, panels and a central spire.",
      location: "Near City Palace, Udaipur",
      lat: 24.5776,
      lng: 73.6828,
    },
  ],
  history: [
    { year: "1559", title: "Udaipur founded", description: "Maharana Udai Singh II founds Udaipur after the fall of Chittorgarh, choosing a defensible, water-rich valley site." },
    { year: "1362", title: "Lake Pichola built", description: "A local banjara built the lake to transport grain, later expanded into the city's defining feature." },
    { year: "1746", title: "Lake Palace built", description: "Maharana Jagat Singh II builds the Lake Palace as a royal summer retreat, now a floating luxury hotel." },
    { year: "1983", title: "Octopussy filmed", description: "The James Bond film brings Udaipur to international attention, filming key scenes at the Lake Palace and Monsoon Palace." },
  ],
  culture: [
    { slug: "mewar-painting", title: "Mewar Miniature Painting", category: "Art", image: img("mewar-painting", 900, 1100), description: "A distinctive school of miniature painting that flourished under Mewar patronage, known for bold colours and courtly scenes." },
    { slug: "mewar-festival", title: "Mewar Festival", category: "Festival", image: img("mewar-festival", 900, 1100), description: "A spring festival celebrating Gangaur, with processions of decorated idols carried to Lake Pichola." },
    { slug: "puppet-shows", title: "Rajasthani Puppetry", category: "Art", image: img("udaipur-puppet", 900, 1100), description: "String-puppet shows performed nightly across the old city, a living folk-art tradition." },
  ],
  food: [
    {
      slug: "dal-baati-udaipur",
      name: "Dal Baati Churma",
      origin: "Rajasthani tradition",
      image: img("udaipur-dal-baati", 1000, 800),
      description: "Udaipur's version of Rajasthan's signature dish — baked wheat rolls with lentils and sweet churma, often served lakeside.",
      ingredients: ["Wheat flour", "Ghee", "Lentils", "Jaggery"],
      taste: "Rich and hearty",
      significance: "A staple of every Rajasthani thali.",
      whereToTry: "Ambrai Ghat restaurants",
    },
    {
      slug: "mirchi-bada",
      name: "Mirchi Bada",
      origin: "Udaipur street food",
      image: img("mirchi-bada", 1000, 800),
      description: "Large green chillies stuffed with spiced potato and deep-fried in gram flour batter — a fiery, beloved local snack.",
      ingredients: ["Green chilli", "Potato", "Gram flour", "Spices"],
      taste: "Spicy and crisp",
      significance: "Sold from carts across the old city as an evening snack.",
      whereToTry: "Bapu Bazaar",
    },
    {
      slug: "lake-view-thali",
      name: "Rajasthani Thali",
      origin: "Home-style Rajasthani cooking",
      image: img("thali", 1000, 800),
      description: "A full-course platter of dal, sabzi, roti, rice and sweets, often served in rooftop restaurants overlooking the lake.",
      ingredients: ["Varies — lentils, vegetables, bread, rice, sweets"],
      taste: "Varied, from spicy to sweet across the courses",
      significance: "The standard way to sample the breadth of Rajasthani home cooking in one sitting.",
      whereToTry: "Ambrai, Upre by 1559 AD",
    },
  ],
  gallery: [
    { image: img("udaipur-g1", 900, 1200), category: "Landmark", caption: "City Palace over Lake Pichola", tall: true },
    { image: img("udaipur-g2", 1200, 900), category: "Landmark", caption: "Lake Palace at dusk" },
    { image: img("udaipur-g3", 900, 1200), category: "Heritage", caption: "Jagdish Temple carvings", tall: true },
    { image: img("udaipur-g4", 1200, 900), category: "Street", caption: "Old city rooftops" },
    { image: img("udaipur-g5", 900, 1200), category: "Culture", caption: "Gangaur festival procession", tall: true },
  ],
  hotels: [
    { slug: "taj-lake-palace", name: "Taj Lake Palace", tier: "Luxury", pricePerNight: 38000, rating: 4.9, image: img("udaipur-hotel-1", 900, 700), lat: 24.5757, lng: 73.6802 },
    { slug: "amet-haveli", name: "Amet Haveli", tier: "Mid-range", pricePerNight: 6500, rating: 4.5, image: img("udaipur-hotel-2", 900, 700), lat: 24.5798, lng: 73.6822 },
    { slug: "hostel-jaipur-udaipur", name: "Backpacker Panda", tier: "Budget", pricePerNight: 600, rating: 4.1, image: img("udaipur-hotel-3", 900, 700), lat: 24.578, lng: 73.6845 },
  ],
  restaurants: [
    { slug: "ambrai", name: "Ambrai", cuisine: "Rajasthani, Lakeside", priceLevel: 3, rating: 4.6, image: img("udaipur-resto-1", 900, 700), lat: 24.5804, lng: 73.6822 },
    { slug: "upre-1559", name: "Upre by 1559 AD", cuisine: "Modern Indian", priceLevel: 4, rating: 4.6, image: img("udaipur-resto-2", 900, 700), lat: 24.577, lng: 73.683 },
    { slug: "millets-of-mewar", name: "Millets of Mewar", cuisine: "Rajasthani, Organic", priceLevel: 2, rating: 4.4, image: img("udaipur-resto-3", 900, 700), lat: 24.5765, lng: 73.6838 },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["Mewari", "English"],
    phrases: [
      { phrase: "Padharo Mhare Desh", translation: "Welcome to my land", phonetic: "pad-haa-ro mha-re desh" },
      { phrase: "Kitno hai?", translation: "How much is it?", phonetic: "kit-no hai" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhun-ya-vaad" },
      { phrase: "Bahut khoobsurat", translation: "Very beautiful", phonetic: "ba-hut khoob-soo-rat" },
    ],
  },
  transport: [
    { mode: "Flight", from: "Delhi/Mumbai", approxTime: "1.5 hours", approxCost: "₹4,000–₹9,000", detail: "Maharana Pratap Airport has good domestic connectivity." },
    { mode: "Train", from: "Jaipur", approxTime: "6–7 hours", approxCost: "₹400–₹1,200", detail: "Overnight and day trains run regularly." },
    { mode: "Car", from: "Jaipur", approxTime: "6 hours", approxCost: "₹4,000–₹6,000", detail: "Scenic drive through rural Rajasthan." },
  ],
  weather: {
    tempC: 27,
    feelsLikeC: 28,
    humidity: 38,
    windKmh: 9,
    condition: "Sunny",
    forecast: [
      { label: "Mon", tempC: 27, condition: "Sunny" },
      { label: "Tue", tempC: 26, condition: "Sunny" },
      { label: "Wed", tempC: 28, condition: "Partly Cloudy" },
      { label: "Thu", tempC: 25, condition: "Cloudy" },
      { label: "Fri", tempC: 27, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Cool and clear" },
    { month: "Feb", score: 2, note: "Pleasant, ideal" },
    { month: "Mar", score: 1, note: "Warming up" },
    { month: "Apr", score: 0, note: "Getting hot" },
    { month: "May", score: 0, note: "Peak heat" },
    { month: "Jun", score: 0, note: "Very hot" },
    { month: "Jul", score: 1, note: "Monsoon, lush and green" },
    { month: "Aug", score: 1, note: "Monsoon, lakes fill up" },
    { month: "Sep", score: 2, note: "Post-monsoon, lakes full" },
    { month: "Oct", score: 2, note: "Excellent weather" },
    { month: "Nov", score: 2, note: "Cool and clear" },
    { month: "Dec", score: 2, note: "Best time to visit" },
  ],
  festivals: [
    { slug: "mewar-festival-fest", name: "Mewar Festival", dateLabel: "March/April", image: img("udaipur-mewar-fest", 900, 700), description: "A spring celebration with processions, folk dances and fireworks over Lake Pichola." },
    { slug: "udaipur-world-music", name: "Udaipur World Music Festival", dateLabel: "February", image: img("udaipur-music-fest", 900, 700), description: "An international music festival held against the backdrop of the City Palace." },
  ],
  shopping: [
    { category: "Art", item: "Miniature paintings", image: img("udaipur-shop-1", 900, 700), priceRange: "₹300–₹15,000", whereToBuy: "Shilpgram, Old City art shops", bargainingTip: "Look for fine brushwork and natural pigments to judge quality." },
    { category: "Textiles", item: "Bandhani & block print", image: img("udaipur-shop-2", 900, 700), priceRange: "₹500–₹5,000", whereToBuy: "Bapu Bazaar, Hathi Pol", bargainingTip: "Hand-block prints have slight imperfections — machine prints are too perfect." },
    { category: "Silver", item: "Tribal silver jewellery", image: img("udaipur-shop-3", 900, 700), priceRange: "₹500–₹10,000", whereToBuy: "Jagdish Temple market", bargainingTip: "Ask for a hallmark or weigh the piece to verify silver content." },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Old city lanes are narrow — watch for motorbike traffic.",
      "Agree on boat ride and rickshaw prices before starting.",
      "Rooftop restaurants can be crowded at sunset — book ahead in peak season.",
      "Carry a light jacket for winter evenings, which get cool quickly by the lake.",
      "Drink bottled or filtered water.",
    ],
  },
};

export const rishikesh: Destination = {
  slug: "rishikesh",
  name: "Rishikesh",
  tagline: "Yoga Capital of the World",
  region: "Uttarakhand",
  country: "India",
  rating: 4.7,
  heroImage: img("rishikesh-hero", 1800, 1100),
  cardImage: img("rishikesh-card", 900, 1100),
  tags: ["Adventure", "Spiritual", "Nature"],
  bestTime: "Sep – Apr",
  center: { lat: 30.0869, lng: 78.2676 },
  quickFacts: { weather: "24°C", budget: "₹", language: "Hindi", stay: "2–4 Days" },
  intro:
    "Rishikesh sits where the Ganges rushes out of the Himalayan foothills, still cold and turquoise before the plains slow it down — a fact that has made the town equally famous for two very different things: whitewater rafting and the Beatles' 1968 stay at an ashram just outside town, which put yoga on the Western map.",
  didYouKnow: [
    "The Beatles stayed at the Maharishi Mahesh Yogi's ashram in Rishikesh in 1968, writing much of the White Album there.",
    "Rishikesh is officially declared the 'Yoga Capital of the World' by the Indian government.",
    "The Ganges here is considered too sacred and too cold in winter for swimming by most pilgrims, but popular for whitewater rafting.",
    "Lakshman Jhula and Ram Jhula are iconic pedestrian suspension bridges over the Ganges.",
  ],
  attractions: [
    {
      slug: "laxman-jhula",
      name: "Laxman Jhula",
      category: "Landmark",
      rating: 4.5,
      image: img("laxman-jhula", 1200, 900),
      duration: "30–45 minutes",
      ticket: "Free",
      hours: "Open 24 hours",
      bestTime: "Sunset",
      about:
        "An iron suspension bridge across the Ganges, said to mark the spot where Lord Lakshman crossed the river on a jute rope. It's now a pedestrian crossing lined with shops and monkeys, offering views up and down the river.",
      architecture: "N/A — a suspension bridge structure.",
      location: "Tapovan, Rishikesh",
      lat: 30.1247,
      lng: 78.3286,
    },
    {
      slug: "triveni-ghat",
      name: "Triveni Ghat",
      category: "Religious",
      rating: 4.7,
      image: img("triveni-ghat", 1200, 900),
      duration: "1 hour",
      ticket: "Free",
      hours: "Open 24 hours, evening aarti around 6-7 PM",
      bestTime: "Evening Ganga Aarti",
      about:
        "Rishikesh's largest and holiest ghat, where the confluence of three rivers is believed to occur. The nightly Ganga Aarti — hundreds of floating lamps set on the water to devotional chanting — is one of the town's most moving experiences.",
      architecture: "N/A — an open riverside ghat.",
      location: "Central Rishikesh",
      lat: 30.1057,
      lng: 78.2955,
    },
    {
      slug: "beatles-ashram",
      name: "Beatles Ashram (Chaurasi Kutia)",
      category: "Historical",
      rating: 4.6,
      image: img("beatles-ashram", 1200, 900),
      duration: "1.5–2 hours",
      ticket: "₹150",
      hours: "8:00 AM – 5:00 PM",
      bestTime: "Morning",
      about:
        "The abandoned ashram where the Beatles stayed in 1968, studying meditation under Maharishi Mahesh Yogi. Now overgrown and covered in fan-painted murals, it's part meditation site, part open-air street art gallery.",
      architecture: "Concrete meditation huts (kutias) in a forested compound, now reclaimed by nature and covered in graffiti art.",
      location: "Swarg Ashram area, Rishikesh",
      lat: 30.1108,
      lng: 78.3013,
    },
  ],
  history: [
    { year: "Ancient", title: "Sage Raibhya's penance", description: "According to legend, Lord Vishnu appeared here in response to the sage Raibhya's penance, giving the town its name — 'Hrishikesh', lord of the senses." },
    { year: "1960s", title: "Beatles put Rishikesh on the map", description: "The Beatles' stay at Maharishi Mahesh Yogi's ashram in 1968 brought international attention to Rishikesh as a centre for meditation and yoga." },
    { year: "2008", title: "Declared Yoga Capital", description: "The Uttarakhand government formally promotes Rishikesh as the 'Yoga Capital of the World', boosting wellness tourism." },
  ],
  culture: [
    { slug: "ganga-aarti", title: "Ganga Aarti", category: "Ritual", image: img("ganga-aarti", 900, 1100), description: "A nightly fire ritual performed on the ghats, offering flame and flowers to the river Ganges amid devotional singing." },
    { slug: "yoga-ashrams", title: "Yoga & Ashram Culture", category: "Tradition", image: img("yoga-culture", 900, 1100), description: "Dozens of ashrams and yoga schools operate in Rishikesh, many offering short courses and internationally recognised teacher training." },
    { slug: "international-yoga-festival", title: "International Yoga Festival", category: "Festival", image: img("yoga-festival", 900, 1100), description: "A week-long festival each March drawing yoga practitioners and teachers from around the world." },
  ],
  food: [
    {
      slug: "sattvic-thali",
      name: "Sattvic Thali",
      origin: "Ashram cuisine",
      image: img("sattvic-thali", 1000, 800),
      description: "A pure vegetarian, no-onion-no-garlic meal following yogic dietary principles, served across the town's many ashram cafes.",
      ingredients: ["Lentils", "Seasonal vegetables", "Rice", "Chapati"],
      taste: "Light, mild and wholesome",
      significance: "Reflects the town's spiritual and health-focused identity.",
      whereToTry: "Ganga Beach Café, ashram canteens",
    },
    {
      slug: "chotiwala",
      name: "Chotiwala Thali",
      origin: "Rishikesh institution since 1958",
      image: img("chotiwala", 1000, 800),
      description: "A famous North Indian thali served at the town's most iconic (and most imitated) restaurant, marked by a mascot in traditional dress out front.",
      ingredients: ["Dal", "Paneer", "Vegetables", "Roti", "Rice"],
      taste: "Rich, home-style North Indian",
      significance: "A Rishikesh landmark since the 1950s, now with several competing branches.",
      whereToTry: "Chotiwala, Swarg Ashram",
    },
    {
      slug: "herbal-tea",
      name: "Himalayan Herbal Tea",
      origin: "Local herbs and Ayurvedic tradition",
      image: img("herbal-tea", 1000, 800),
      description: "A blend of local Himalayan herbs, served hot in the many rooftop cafes overlooking the Ganges.",
      ingredients: ["Tulsi", "Ginger", "Cinnamon", "Local herbs"],
      taste: "Warm, aromatic and mildly spiced",
      significance: "A staple of Rishikesh's cafe culture.",
      whereToTry: "Any riverside rooftop cafe in Tapovan or Laxman Jhula",
    },
  ],
  gallery: [
    { image: img("rishikesh-g1", 900, 1200), category: "Landmark", caption: "Laxman Jhula over the Ganges", tall: true },
    { image: img("rishikesh-g2", 1200, 900), category: "Ritual", caption: "Ganga Aarti at Triveni Ghat" },
    { image: img("rishikesh-g3", 900, 1200), category: "Adventure", caption: "Whitewater rafting on the Ganges", tall: true },
    { image: img("rishikesh-g4", 1200, 900), category: "Culture", caption: "Beatles Ashram murals" },
    { image: img("rishikesh-g5", 900, 1200), category: "Nature", caption: "Foothills of the Himalayas", tall: true },
  ],
  hotels: [
    { slug: "ananda-himalayas", name: "Ananda in the Himalayas", tier: "Luxury", pricePerNight: 32000, rating: 4.9, image: img("rishikesh-hotel-1", 900, 700), lat: 30.0783, lng: 78.2456 },
    { slug: "ganga-view-rishikesh", name: "Ganga View Resort", tier: "Mid-range", pricePerNight: 3200, rating: 4.3, image: img("rishikesh-hotel-2", 900, 700), lat: 30.1225, lng: 78.3252 },
    { slug: "backpackers-den", name: "Backpackers' Den", tier: "Budget", pricePerNight: 500, rating: 4.2, image: img("rishikesh-hotel-3", 900, 700), lat: 30.1195, lng: 78.3223 },
  ],
  restaurants: [
    { slug: "ganga-beach-cafe", name: "Ganga Beach Café", cuisine: "Multi-cuisine, Vegetarian", priceLevel: 2, rating: 4.5, image: img("rishikesh-resto-1", 900, 700), lat: 30.1237, lng: 78.3268 },
    { slug: "chotiwala-resto", name: "Chotiwala", cuisine: "North Indian", priceLevel: 2, rating: 4.3, image: img("rishikesh-resto-2", 900, 700), lat: 30.1108, lng: 78.3013 },
    { slug: "little-buddha-cafe", name: "Little Buddha Café", cuisine: "Continental, Israeli", priceLevel: 2, rating: 4.4, image: img("rishikesh-resto-3", 900, 700), lat: 30.1257, lng: 78.3283 },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["Garhwali", "English"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nuh-mas-tay" },
      { phrase: "Ganga Maiya ki Jai", translation: "Hail to Mother Ganges", phonetic: "gun-ga mai-ya ki jai" },
      { phrase: "Kitna hai?", translation: "How much is it?", phonetic: "kit-na hai" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhun-ya-vaad" },
    ],
  },
  transport: [
    { mode: "Flight", from: "Delhi", approxTime: "1 hour to Dehradun + 45 min drive", approxCost: "₹3,500–₹8,000", detail: "Jolly Grant Airport, Dehradun is the nearest airport." },
    { mode: "Train", from: "Delhi", approxTime: "5–6 hours", approxCost: "₹300–₹1,000", detail: "Direct trains to Rishikesh or Haridwar station." },
    { mode: "Bus", from: "Delhi", approxTime: "6–7 hours", approxCost: "₹400–₹900", detail: "Regular Volvo and state buses from Delhi's ISBT." },
  ],
  weather: {
    tempC: 24,
    feelsLikeC: 24,
    humidity: 55,
    windKmh: 8,
    condition: "Partly Cloudy",
    forecast: [
      { label: "Mon", tempC: 24, condition: "Partly Cloudy" },
      { label: "Tue", tempC: 23, condition: "Sunny" },
      { label: "Wed", tempC: 25, condition: "Sunny" },
      { label: "Thu", tempC: 22, condition: "Rainy" },
      { label: "Fri", tempC: 24, condition: "Partly Cloudy" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 1, note: "Cold, clear mountain air" },
    { month: "Feb", score: 2, note: "Pleasant and cool" },
    { month: "Mar", score: 2, note: "Ideal for yoga and rafting season starts" },
    { month: "Apr", score: 2, note: "Warm and clear" },
    { month: "May", score: 1, note: "Getting hot" },
    { month: "Jun", score: 0, note: "Hot, rafting paused pre-monsoon" },
    { month: "Jul", score: 0, note: "Monsoon, rafting suspended" },
    { month: "Aug", score: 0, note: "Heavy monsoon" },
    { month: "Sep", score: 2, note: "Post-monsoon, rafting resumes" },
    { month: "Oct", score: 2, note: "Excellent weather" },
    { month: "Nov", score: 2, note: "Cool and clear" },
    { month: "Dec", score: 1, note: "Cold but scenic" },
  ],
  festivals: [
    { slug: "international-yoga-fest", name: "International Yoga Festival", dateLabel: "1–7 March", image: img("rishikesh-yoga-fest", 900, 700), description: "A week of yoga, meditation and wellness workshops drawing practitioners from around the world." },
    { slug: "makar-sankranti-rishikesh", name: "Makar Sankranti", dateLabel: "14 January", image: img("rishikesh-sankranti", 900, 700), description: "Pilgrims take a holy dip in the Ganges to mark the sun's transit, one of the town's biggest pilgrim gatherings." },
  ],
  shopping: [
    { category: "Wellness", item: "Ayurvedic oils & herbs", image: img("rishikesh-shop-1", 900, 700), priceRange: "₹100–₹2,000", whereToBuy: "Ram Jhula, Swarg Ashram market", bargainingTip: "Buy from established Ayurvedic pharmacies for authenticity." },
    { category: "Spiritual", item: "Rudraksha malas", image: img("rishikesh-shop-2", 900, 700), priceRange: "₹100–₹5,000", whereToBuy: "Stalls near Triveni Ghat", bargainingTip: "Bead size and 'mukhi' count drive price — ask for authenticity certificates on expensive pieces." },
    { category: "Clothing", item: "Yoga wear & prayer shawls", image: img("rishikesh-shop-3", 900, 700), priceRange: "₹200–₹1,500", whereToBuy: "Laxman Jhula market", bargainingTip: "Check stitching and fabric weight before buying." },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Only raft with licensed operators registered with the Uttarakhand tourism board.",
      "The Ganges current is strong and cold even in shallow areas — heed posted warnings.",
      "Monkeys near Laxman Jhula can be aggressive around food — keep bags zipped.",
      "Alcohol and meat are prohibited in the Swarg Ashram/Ram Jhula area out of respect for its spiritual character.",
      "Carry warm layers in winter — mountain evenings get cold quickly.",
    ],
  },
};

export const extraDestinations: Destination[] = [delhi, agra, udaipur, rishikesh];
