import { Destination } from "./types";
import { extraDestinations } from "./mock-data-extra";

const img = (seed: string, w = 1200, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const jaipur: Destination = {
  slug: "jaipur",
  name: "Jaipur",
  tagline: "The Pink City",
  region: "Rajasthan",
  country: "India",
  rating: 4.8,
  heroImage: "/images/jaipur-hero.jpg",
  cardImage: img("jaipur-card", 900, 1100),
  tags: ["Heritage", "Cuisine", "Culture"],
  bestTime: "Oct – Mar",
  center: { lat: 26.9124, lng: 75.7873 },
  quickFacts: {
    weather: "31°C",
    budget: "₹₹",
    language: "Hindi",
    stay: "3–4 Days",
  },
  intro:
    "Jaipur was built as a statement — a capital laid out on a grid a century before urban planning was a discipline, and painted the colour of welcome for a visiting prince in 1876. What's left is a city where sandstone forts sit on the ridgelines above bazaars still selling the same block-printed cotton and blue pottery its founder's court once traded.",
  didYouKnow: [
    "Jaipur was founded in 1727 by Sawai Jai Singh II, a Rajput king and keen astronomer.",
    "The whole Old City was painted pink in 1876 to welcome the Prince of Wales — and the colour stuck by royal decree.",
    "Jantar Mantar's stone sundial can tell the time accurate to two seconds.",
    "Jaipur was one of India's first planned cities, laid out on Vedic architectural principles in nine rectangular blocks.",
    "Hawa Mahal has 953 small windows, built so royal women could watch street life unseen.",
    "The City Palace complex still houses the royal family in a private wing today.",
  ],
  attractions: [
    {
      slug: "amber-fort",
      name: "Amber Fort",
      category: "Historical",
      rating: 4.8,
      image: img("amber-fort", 1200, 900),
      duration: "2–3 hours",
      ticket: "₹200 (Indians) / ₹500 (Foreigners)",
      hours: "8:00 AM – 5:30 PM",
      bestTime: "Early morning, before the tour buses",
      about:
        "Amber Fort rises out of the Aravalli hills in tiers of honey-gold sandstone and white marble, its ramparts folding into the ridge like they grew there. Built as the seat of Rajput power before the capital moved to Jaipur, it pairs the muscle of a hill fortress with the delicacy of a palace — mirrored halls, latticed courtyards, gardens laid out in the Mughal style.",
      architecture:
        "A blend of Rajput and Mughal architecture: red sandstone and pale marble, sweeping ramparts, and the Sheesh Mahal — a hall of mirrors designed so a single candle could light the whole room in reflected starlight.",
      location: "Devisinghpura, Amer, Jaipur",
      lat: 26.9855,
      lng: 75.8513,
    },
    {
      slug: "city-palace",
      name: "City Palace",
      category: "Heritage",
      rating: 4.7,
      image: img("city-palace", 1200, 900),
      duration: "1.5–2 hours",
      ticket: "₹200 (Indians) / ₹700 (Foreigners)",
      hours: "9:30 AM – 5:00 PM",
      bestTime: "Late afternoon light",
      about:
        "Still home to Jaipur's royal family, the City Palace sits at the heart of the grid Jai Singh II drew up in 1727. Courtyards open into courtyards, each one a little more ornate than the last, ending in the Chandra Mahal, seven storeys of private apartments still partly in royal use.",
      architecture:
        "A working fusion of Rajasthani and Mughal styles, with later European and Chinese influences added by successive maharajas — arched gateways, peacock-motif doors, and marble-columned reception halls.",
      location: "Old City, Jaipur",
      lat: 26.9255,
      lng: 75.8237,
    },
    {
      slug: "hawa-mahal",
      name: "Hawa Mahal",
      category: "Architecture",
      rating: 4.8,
      image: img("hawa-mahal", 1200, 900),
      duration: "45 minutes",
      ticket: "₹50 (Indians) / ₹200 (Foreigners)",
      hours: "9:00 AM – 4:30 PM",
      bestTime: "Sunrise, when the sandstone turns rose-gold",
      about:
        "A five-storey screen more than a building — the Hawa Mahal's honeycomb facade of 953 latticed windows was built in 1799 so the women of the royal court could watch festivals and street life on the bazaar below without being seen themselves.",
      architecture:
        "Red and pink sandstone in a honeycomb of small, semi-octagonal windows (jharokhas), designed to funnel a constant breeze through the palace — hence 'Palace of Winds'.",
      location: "Badi Choupad, Old City, Jaipur",
      lat: 26.9239,
      lng: 75.8267,
    },
    {
      slug: "jantar-mantar",
      name: "Jantar Mantar",
      category: "Historical",
      rating: 4.6,
      image: img("jantar-mantar", 1200, 900),
      duration: "1 hour",
      ticket: "₹50 (Indians) / ₹200 (Foreigners)",
      hours: "9:00 AM – 4:30 PM",
      bestTime: "Midday, to see the instruments in full sun",
      about:
        "A UNESCO World Heritage observatory of nineteen astronomical instruments, built from stone and marble by the astronomer-king Jai Singh II. Nothing here is decorative — each structure calculates time, tracks eclipses, or maps the position of stars, some still accurate today.",
      architecture:
        "Monumental geometric instruments in stone and marble, including the Samrat Yantra, the world's largest stone sundial, accurate to two seconds.",
      location: "Adjacent to City Palace, Jaipur",
      lat: 26.9246,
      lng: 75.8247,
    },
    {
      slug: "jal-mahal",
      name: "Jal Mahal",
      category: "Landmark",
      rating: 4.7,
      image: img("jal-mahal", 1200, 900),
      duration: "30 minutes (viewing)",
      ticket: "Free to view from the shore",
      hours: "Viewable 24 hours",
      bestTime: "Sunset",
      about:
        "A red sandstone palace that appears to float in the middle of Man Sagar Lake — four of its five floors sit underwater. Once a royal duck-hunting lodge, it's now viewed from the shoreline, framed by the Nahargarh hills behind it.",
      architecture:
        "Rajput architecture with a rooftop garden and chhatri pavilions, built almost entirely below the waterline as a flood-control measure for the palace above.",
      location: "Man Sagar Lake, Jaipur",
      lat: 26.9536,
      lng: 75.846,
    },
  ],
  history: [
    {
      year: "1727",
      title: "Jaipur is founded",
      description:
        "Sawai Jai Singh II, ruler of Amber, lays out a new capital on the plains below his hill fort — one of India's first planned cities, built on a grid according to Vedic principles.",
    },
    {
      year: "1727–1734",
      title: "The grid takes shape",
      description:
        "The city is divided into nine rectangular blocks (chowkri), with wide avenues, dedicated markets, and palaces — an unusually deliberate piece of urban design for its era.",
    },
    {
      year: "1799",
      title: "Hawa Mahal is built",
      description:
        "Sawai Pratap Singh commissions the Palace of Winds, giving the royal women a place to observe the city's daily life and processions from behind a screen of latticed windows.",
    },
    {
      year: "1876",
      title: "The city turns pink",
      description:
        "Maharaja Ram Singh has the entire Old City painted terracotta pink to welcome the Prince of Wales. The colour becomes law, and the tradition of repainting continues today.",
    },
    {
      year: "1949",
      title: "Jaipur joins independent India",
      description:
        "The princely state of Jaipur accedes to the Union of India, and the city becomes the capital of the newly formed state of Rajasthan.",
    },
    {
      year: "Today",
      title: "Modern Jaipur",
      description:
        "A UNESCO World Heritage City that balances a living Old City — still trading textiles, gems and blue pottery — with a fast-growing modern metropolis around it.",
    },
  ],
  culture: [
    {
      slug: "ghoomar",
      title: "Ghoomar",
      category: "Dance",
      image: img("ghoomar", 900, 1100),
      description:
        "A swirling folk dance performed by women in flowing ghagras, originally a ritual to welcome goddess Sati. Today it opens weddings and festivals across Rajasthan, the fabric of the skirt itself part of the choreography.",
    },
    {
      slug: "blue-pottery",
      title: "Blue Pottery",
      category: "Handicraft",
      image: img("blue-pottery", 900, 1100),
      description:
        "A Persian-influenced craft using no clay at all — quartz, glue and a cobalt-oxide glaze instead. Jaipur adopted it in the 19th century and it's now one of the city's signature exports.",
    },
    {
      slug: "bandhani",
      title: "Bandhani & Textiles",
      category: "Clothing",
      image: img("bandhani", 900, 1100),
      description:
        "Tie-dye textiles made by hand-knotting cloth before dyeing, producing the tiny dotted patterns seen in traditional Rajasthani turbans and odhnis. A single sari can take weeks of hand-tying.",
    },
    {
      slug: "teej",
      title: "Teej Festival",
      category: "Festival",
      image: img("teej", 900, 1100),
      description:
        "A monsoon festival honouring Goddess Parvati, marked with a grand procession through the Old City — decorated elephants, folk dancers, and swings hung from trees for the women observing the fast.",
    },
    {
      slug: "puppetry",
      title: "Kathputli Puppetry",
      category: "Art",
      image: img("puppetry", 900, 1100),
      description:
        "String-puppet theatre dating back centuries, performed by the Bhat community and once used to spread news and satire through royal courts and villages alike.",
    },
    {
      slug: "rajasthani-cuisine",
      title: "Royal Cuisine",
      category: "Tradition",
      image: img("royal-cuisine", 900, 1100),
      description:
        "Born from a desert climate and a warrior court — long-lasting, ghee-rich dishes designed to survive travel, still cooked in the same clay ovens and copper vessels today.",
    },
  ],
  food: [
    {
      slug: "dal-baati-churma",
      name: "Dal Baati Churma",
      origin: "Rajasthani royal and rural kitchens",
      image: img("dal-baati", 1000, 800),
      description:
        "Rajasthan's signature dish: hard-baked wheat rolls (baati) cracked open and doused in ghee, served with spiced lentils (dal) and a sweet crumbled-wheat churma on the side.",
      ingredients: ["Wheat flour", "Ghee", "Mixed lentils", "Jaggery", "Whole spices"],
      taste: "Earthy and rich, balanced by the churma's sweetness",
      significance:
        "Originally cooked over campfires by soldiers whose baatis could keep for days — now the centrepiece of every Rajasthani celebration.",
      whereToTry: "Old City thalis, especially around Chandpole",
    },
    {
      slug: "pyaz-kachori",
      name: "Pyaz Kachori",
      origin: "Jaipur street food",
      image: img("kachori", 1000, 800),
      description:
        "A flaky, deep-fried pastry stuffed with a spiced onion filling — Jaipur's definitive breakfast, best eaten hot with tamarind and mint chutney.",
      ingredients: ["Refined flour", "Onions", "Fennel", "Chilli", "Gram flour"],
      taste: "Crisp shell, peppery-sweet filling",
      significance:
        "A morning ritual across the city — queues form outside the best-known stalls before 9am.",
      whereToTry: "Rawat Mishthan Bhandar, Station Road",
    },
    {
      slug: "ghewar",
      name: "Ghewar",
      origin: "Rajasthani festival sweets",
      image: img("ghewar", 1000, 800),
      description:
        "A disc-shaped, honeycombed sweet made by dripping batter into hot ghee, then soaked in sugar syrup and topped with rabri or nuts. Traditionally made for Teej and Raksha Bandhan.",
      ingredients: ["Refined flour", "Ghee", "Sugar syrup", "Rabri (reduced milk)", "Pistachio"],
      taste: "Crisp, porous and syrup-soaked, richly sweet",
      significance: "Tied closely to the monsoon festival season, especially Teej.",
      whereToTry: "Laxmi Mishthan Bhandar, Johari Bazaar",
    },
    {
      slug: "laal-maas",
      name: "Laal Maas",
      origin: "Rajput royal kitchens",
      image: img("laal-maas", 1000, 800),
      description:
        "A fiery mutton curry built on Mathania red chillies, once a hunter's dish for using the day's game. The gravy gets its deep red colour and heat entirely from the chilli, not tomato.",
      ingredients: ["Mutton", "Mathania red chillies", "Yogurt", "Garlic", "Ghee"],
      taste: "Intensely spicy, tangy and smoky",
      significance:
        "A Rajput hunting-camp dish elevated into royal-kitchen fare — still a test of a cook's spice handling.",
      whereToTry: "Suvarna Mahal, or family-run Rajasthani kitchens in the Old City",
    },
    {
      slug: "lassi",
      name: "Lassi",
      origin: "North Indian, ubiquitous in Rajasthan",
      image: img("lassi", 1000, 800),
      description:
        "A thick, chilled yogurt drink served in a clay kulhad, sometimes topped with a slab of malai (cream). Jaipur's versions lean thicker and sweeter than most.",
      ingredients: ["Yogurt", "Sugar", "Cardamom", "Cream"],
      taste: "Cool, thick and mildly sweet",
      significance: "A daily antidote to Rajasthan's dry heat, served everywhere from street carts to weddings.",
      whereToTry: "Lassiwala, M.I. Road",
    },
  ],
  gallery: [
    { image: img("gal-1", 900, 1200), category: "Architecture", caption: "Amber Fort ramparts at dawn", tall: true },
    { image: img("gal-2", 900, 700), category: "Food", caption: "Kachori frying at a Old City stall" },
    { image: img("gal-3", 900, 1100), category: "Culture", caption: "Ghoomar dancers at a wedding" },
    { image: img("gal-4", 900, 700), category: "Attractions", caption: "Hawa Mahal facade" },
    { image: img("gal-5", 900, 1300), category: "Markets", caption: "Bandhani textiles in Johari Bazaar", tall: true },
    { image: img("gal-6", 900, 700), category: "Nature", caption: "Sunset over Jal Mahal" },
    { image: img("gal-7", 900, 900), category: "Festivals", caption: "Teej procession" },
    { image: img("gal-8", 900, 1200), category: "Architecture", caption: "City Palace courtyard", tall: true },
    { image: img("gal-9", 900, 700), category: "Food", caption: "Ghewar stacked for Teej" },
  ],
  hotels: [
    {
      slug: "royal-heritage-haveli",
      name: "Royal Heritage Haveli",
      tier: "Budget",
      pricePerNight: 1800,
      rating: 4.3,
      image: img("hotel-budget", 900, 700),
      lat: 26.9231,
      lng: 75.8258,
    },
    {
      slug: "trident-jaipur",
      name: "Trident Jaipur",
      tier: "Mid-range",
      pricePerNight: 4200,
      rating: 4.6,
      image: img("hotel-midrange", 900, 700),
      lat: 26.8929,
      lng: 75.8054,
    },
    {
      slug: "rambagh-heritage-palace",
      name: "Rambagh Heritage Palace",
      tier: "Luxury",
      pricePerNight: 15500,
      rating: 4.9,
      image: img("hotel-luxury", 900, 700),
      lat: 26.8973,
      lng: 75.8095,
    },
  ],
  restaurants: [
    {
      slug: "chokhi-dhani-thali",
      name: "Chokhi Dhani",
      cuisine: "Rajasthani",
      priceLevel: 2,
      rating: 4.5,
      image: img("resto-rajasthani", 900, 700),
      lat: 26.7783,
      lng: 75.7527,
    },
    {
      slug: "peacock-rooftop",
      name: "Peacock Rooftop",
      cuisine: "Multi-cuisine",
      priceLevel: 3,
      rating: 4.4,
      image: img("resto-rooftop", 900, 700),
      lat: 26.9258,
      lng: 75.8236,
    },
    {
      slug: "anokhi-cafe",
      name: "Anokhi Café",
      cuisine: "Café",
      priceLevel: 2,
      rating: 4.6,
      image: img("resto-cafe", 900, 700),
      lat: 26.907,
      lng: 75.8043,
    },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["English", "Rajasthani (Marwari/Dhundhari dialects)"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nə-məs-teɪ" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhən-yə-vaad" },
      { phrase: "Kitne ka hai?", translation: "How much is this?", phonetic: "kit-ne kaa hai" },
      { phrase: "Kahan hai?", translation: "Where is it?", phonetic: "kə-haan hai" },
      { phrase: "Haan / Nahin", translation: "Yes / No", phonetic: "haan / nə-heen" },
      { phrase: "Maaf kijiye", translation: "Excuse me / Sorry", phonetic: "maaf kee-jee-ye" },
    ],
  },
  transport: [
    {
      mode: "Flight",
      from: "New Delhi",
      approxTime: "1 hr",
      approxCost: "₹3,000–₹6,000",
      detail: "Multiple daily flights into Jaipur International Airport (JAI).",
    },
    {
      mode: "Train",
      from: "New Delhi",
      approxTime: "4.5–5.5 hrs",
      approxCost: "₹400–₹1,500",
      detail: "Frequent trains from Delhi's main stations, including fast options like Ajmer Shatabdi.",
    },
    {
      mode: "Bus",
      from: "New Delhi",
      approxTime: "5.5–6.5 hrs",
      approxCost: "₹500–₹1,200",
      detail: "AC Volvo and state-run buses run overnight and through the day.",
    },
    {
      mode: "Car",
      from: "New Delhi",
      approxTime: "5–6 hrs",
      approxCost: "₹4,000–₹6,000 (cab, one-way)",
      detail: "Via NH48, a well-maintained expressway-grade highway.",
    },
  ],
  weather: {
    tempC: 31,
    feelsLikeC: 33,
    humidity: 48,
    windKmh: 12,
    condition: "Sunny",
    forecast: [
      { label: "Today", tempC: 31, condition: "Sunny" },
      { label: "Tomorrow", tempC: 30, condition: "Partly Cloudy" },
      { label: "Wed", tempC: 28, condition: "Rainy" },
      { label: "Thu", tempC: 29, condition: "Partly Cloudy" },
      { label: "Fri", tempC: 32, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Cool, clear, ideal for sightseeing." },
    { month: "Feb", score: 2, note: "Pleasant days, cool evenings." },
    { month: "Mar", score: 1, note: "Warming up; still comfortable mornings." },
    { month: "Apr", score: 0, note: "Hot — best for indoor sights only." },
    { month: "May", score: 0, note: "Peak heat, often above 40°C." },
    { month: "Jun", score: 0, note: "Very hot, monsoon builds late month." },
    { month: "Jul", score: 1, note: "Monsoon — green, fewer crowds, humid." },
    { month: "Aug", score: 1, note: "Monsoon continues, Teej festival." },
    { month: "Sep", score: 1, note: "Monsoon tapering off." },
    { month: "Oct", score: 2, note: "Post-monsoon, festive season begins." },
    { month: "Nov", score: 2, note: "Diwali season, pleasant weather." },
    { month: "Dec", score: 2, note: "Cool and dry, peak tourist season." },
  ],
  festivals: [
    {
      slug: "diwali",
      name: "Diwali",
      dateLabel: "October / November",
      image: img("festival-diwali", 900, 700),
      description:
        "The festival of lights transforms the Old City — every haveli and bazaar strung with diyas and fairy lights, fireworks over the skyline.",
    },
    {
      slug: "teej",
      name: "Teej Festival",
      dateLabel: "July / August",
      image: img("festival-teej", 900, 700),
      description:
        "A grand procession honoring Goddess Parvati winds through the city with decorated elephants, folk dancers and music.",
    },
    {
      slug: "elephant-festival",
      name: "Jaipur Elephant Festival",
      dateLabel: "March",
      image: img("festival-elephant", 900, 700),
      description:
        "Painted elephants parade through the city ahead of Holi, alongside folk performances and elephant polo.",
    },
    {
      slug: "kite-festival",
      name: "International Kite Festival",
      dateLabel: "January",
      image: img("festival-kite", 900, 700),
      description:
        "Skies over Jaipur fill with kites for Makar Sankranti — rooftop parties and competitions across the city.",
    },
  ],
  shopping: [
    {
      category: "Textiles",
      item: "Block-printed cotton & Bandhani",
      image: img("shop-textiles", 900, 700),
      priceRange: "₹300–₹3,000",
      whereToBuy: "Johari Bazaar, Bapu Bazaar",
      bargainingTip: "Start at 40–50% of the quoted price and settle around 60–70%.",
    },
    {
      category: "Jewelry",
      item: "Kundan & Meenakari jewelry",
      image: img("shop-jewelry", 900, 700),
      priceRange: "₹500–₹50,000+",
      whereToBuy: "Johari Bazaar (Jaipur's historic jewelers' market)",
      bargainingTip: "Ask for a certificate for anything gemstone or gold.",
    },
    {
      category: "Handicrafts",
      item: "Blue pottery",
      image: img("shop-pottery", 900, 700),
      priceRange: "₹200–₹2,500",
      whereToBuy: "Kripal Kumbh, Bapu Bazaar",
      bargainingTip: "Fixed-price government emporiums are reliable but pricier.",
    },
    {
      category: "Footwear",
      item: "Mojari (traditional juttis)",
      image: img("shop-mojari", 900, 700),
      priceRange: "₹400–₹2,000",
      whereToBuy: "Mochi Bazaar, Nehru Bazaar",
      bargainingTip: "Check stitching quality — hand-stitched soles last longer.",
    },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Dress modestly when visiting temples and religious sites.",
      "Agree on auto-rickshaw/taxi fares before the ride, or use a metered app.",
      "Keep valuables and documents secured; use hotel safes where available.",
      "Stay hydrated and carry sun protection, especially Mar–Jun.",
      "Drink bottled or filtered water.",
      "Save your hotel's address in Hindi to show drivers if needed.",
    ],
  },
};

export const goa: Destination = {
  slug: "goa",
  name: "Goa",
  tagline: "Sun, Sea & Portuguese Soul",
  region: "Goa",
  country: "India",
  rating: 4.6,
  heroImage: img("goa-hero", 1800, 1100),
  cardImage: img("goa-card", 900, 1100),
  tags: ["Beaches", "Nightlife", "Heritage"],
  bestTime: "Nov – Feb",
  center: { lat: 15.4909, lng: 73.8278 },
  quickFacts: { weather: "29°C", budget: "₹₹", language: "Konkani", stay: "4–5 Days" },
  intro:
    "Goa runs on two clocks at once — the unhurried rhythm of a fishing coast that's barely changed in a century, and the after-dark pulse of beach shacks and clubs that made it India's party capital. Four hundred and fifty years of Portuguese rule left whitewashed churches and a Latin ease that no other Indian state shares; the sea did the rest.",
  didYouKnow: [
    "Goa was a Portuguese colony for 451 years — longer than British rule over the rest of India — and only became part of India in 1961.",
    "The Basilica of Bom Jesus holds the mortal remains of St. Francis Xavier, exposed to public veneration once a decade.",
    "Goa has the highest per-capita income of any Indian state.",
    "Dudhsagar Falls is one of India's tallest waterfalls, at roughly 310 metres.",
    "Goan Catholic weddings and Hindu temple festivals both draw huge crowds — the state's calendar runs on both.",
  ],
  attractions: [
    {
      slug: "baga-beach",
      name: "Baga Beach",
      category: "Beach",
      rating: 4.5,
      image: img("baga-beach", 1200, 900),
      duration: "Half day",
      ticket: "Free",
      hours: "Open 24 hours",
      bestTime: "Late afternoon into sunset",
      about:
        "North Goa's liveliest stretch of sand — beach shacks shoulder to shoulder, water sports by day, and some of the state's best-known clubs a short walk inland once the sun goes down.",
      architecture: "N/A — open beach and shack-front strip.",
      location: "Baga, North Goa",
      lat: 15.5553,
      lng: 73.7517,
    },
    {
      slug: "fort-aguada",
      name: "Fort Aguada",
      category: "Historical",
      rating: 4.6,
      image: img("fort-aguada", 1200, 900),
      duration: "1.5 hours",
      ticket: "Free",
      hours: "8:30 AM – 6:00 PM",
      bestTime: "Sunset, for the lighthouse view over the Arabian Sea",
      about:
        "A 17th-century Portuguese fort built to guard against Dutch and Maratha naval attacks and to store fresh water for ships (hence 'aguada'). Its lighthouse is one of the oldest of its kind in Asia.",
      architecture:
        "Laterite-stone bastions and a four-storey lighthouse, built low and thick-walled to withstand cannon fire.",
      location: "Sinquerim, Bardez, North Goa",
      lat: 15.4925,
      lng: 73.7738,
    },
    {
      slug: "basilica-of-bom-jesus",
      name: "Basilica of Bom Jesus",
      category: "Heritage",
      rating: 4.7,
      image: img("bom-jesus", 1200, 900),
      duration: "1 hour",
      ticket: "Free",
      hours: "9:00 AM – 6:30 PM",
      bestTime: "Weekday mornings, before tour groups arrive",
      about:
        "A UNESCO World Heritage church in Old Goa holding the remains of St. Francis Xavier. One of the best-preserved examples of Baroque architecture in Asia, still an active place of worship after more than 400 years.",
      architecture:
        "Baroque facade in laterite covered with lime plaster, with an ornate gilded main altar dedicated to St. Ignatius Loyola.",
      location: "Old Goa",
      lat: 15.5009,
      lng: 73.9116,
    },
    {
      slug: "dudhsagar-falls",
      name: "Dudhsagar Falls",
      category: "Nature",
      rating: 4.8,
      image: img("dudhsagar", 1200, 900),
      duration: "3–4 hours (with travel)",
      ticket: "Jeep safari ~₹500 per person",
      hours: "9:00 AM – 4:00 PM (weather dependent)",
      bestTime: "Just after monsoon (Oct), when the falls run full",
      about:
        "A four-tiered waterfall on the Goa–Karnataka border, dropping around 310 metres through the Bhagwan Mahavir Wildlife Sanctuary. Reached by jeep safari over a rough forest track and a river crossing.",
      architecture: "N/A — natural waterfall within a wildlife sanctuary.",
      location: "Bhagwan Mahavir Wildlife Sanctuary, Sanguem",
      lat: 15.3144,
      lng: 74.3144,
    },
    {
      slug: "anjuna-flea-market",
      name: "Anjuna Flea Market",
      category: "Market",
      rating: 4.4,
      image: img("anjuna-market", 1200, 900),
      duration: "2–3 hours",
      ticket: "Free entry",
      hours: "Wednesdays, 8:00 AM – sunset",
      bestTime: "Morning, before the heat and crowds build",
      about:
        "A weekly beachside bazaar going back to the hippie era of the 1960s — clothing, jewellery, spices, and souvenirs from vendors across India and beyond, with live music drifting between the stalls.",
      architecture: "N/A — open-air market on clifftop and beach terrain.",
      location: "Anjuna, North Goa",
      lat: 15.5738,
      lng: 73.7405,
    },
  ],
  history: [
    {
      year: "1510",
      title: "The Portuguese arrive",
      description:
        "Afonso de Albuquerque captures Goa from the Bijapur Sultanate, establishing it as the capital of Portuguese India.",
    },
    {
      year: "1542",
      title: "St. Francis Xavier arrives",
      description:
        "The Jesuit missionary lands in Goa, beginning a wave of church-building and conversion that shaped Goan Catholic identity.",
    },
    {
      year: "17th century",
      title: "Old Goa's golden age",
      description:
        "Old Goa becomes one of the richest cities in Asia, rivaling Lisbon — before repeated epidemics force the capital to move to Panjim.",
    },
    {
      year: "1961",
      title: "Operation Vijay",
      description:
        "The Indian Army annexes Goa, ending 451 years of Portuguese rule and folding the territory into the Indian Union.",
    },
    {
      year: "1987",
      title: "Statehood",
      description: "Goa becomes India's 25th state, separate from the Union Territory it had been since 1961.",
    },
    {
      year: "Today",
      title: "Modern Goa",
      description:
        "A tourism-driven economy balancing beach-shack culture, EDM festivals, and a quieter Portuguese-era heritage still visible in its churches and old quarters.",
    },
  ],
  culture: [
    {
      slug: "goan-catholic-heritage",
      title: "Goan Catholic Heritage",
      category: "Tradition",
      image: img("goa-catholic", 900, 1100),
      description:
        "Roughly a quarter of Goans are Catholic, a legacy of Portuguese rule — village feasts, church architecture, and Latin-script Konkani hymns exist nowhere else in India.",
    },
    {
      slug: "fado-and-goan-music",
      title: "Goan Music",
      category: "Music",
      image: img("goa-music", 900, 1100),
      description:
        "A blend of Konkani folk, Portuguese fado influence, and — since the 1960s — the trance and EDM scene that grew out of Goa's hippie era, still centered on Anjuna and Vagator.",
    },
    {
      slug: "susegad",
      title: "Susegad",
      category: "Lifestyle",
      image: img("goa-susegad", 900, 1100),
      description:
        "A Goan term (from Portuguese 'sossegado') for a relaxed, unhurried approach to life — often cited as the philosophy behind Goa's famously laid-back pace.",
    },
    {
      slug: "carnival",
      title: "Goa Carnival",
      category: "Festival",
      image: img("goa-carnival", 900, 1100),
      description:
        "A pre-Lent street festival of parades, floats and music introduced under Portuguese rule — the only state-sanctioned Carnival celebration in India.",
    },
  ],
  food: [
    {
      slug: "goan-fish-curry",
      name: "Goan Fish Curry",
      origin: "Coastal Goan home cooking",
      image: img("goan-fish-curry", 1000, 800),
      description:
        "A tangy, coconut-and-kokum-based curry built around the catch of the day, served with steamed rice — the everyday backbone of a Goan meal.",
      ingredients: ["Fresh fish", "Coconut", "Kokum", "Red chillies", "Tamarind"],
      taste: "Tangy, mildly spicy, rich with coconut",
      significance: "The default home-cooked meal in most Goan households, eaten almost daily.",
      whereToTry: "Family-run 'khanavals' (local eateries) away from the tourist strip",
    },
    {
      slug: "vindaloo",
      name: "Pork Vindaloo",
      origin: "Portuguese-Goan fusion",
      image: img("vindaloo", 1000, 800),
      description:
        "A fiery vinegar-and-garlic pork curry descended from a Portuguese dish ('carne de vinha d'alhos'), adapted with local chillies and spices into something distinctly Goan.",
      ingredients: ["Pork", "Vinegar", "Garlic", "Kashmiri chillies", "Cumin"],
      taste: "Sharp, sour, deeply spiced",
      significance: "A signature of Goan Catholic cuisine, usually reserved for feasts.",
      whereToTry: "Ritz Classic, Panjim",
    },
    {
      slug: "bebinca",
      name: "Bebinca",
      origin: "Goan Catholic dessert",
      image: img("bebinca", 1000, 800),
      description:
        "A dense, multi-layered baked pudding made one thin layer at a time — traditionally 7 or 16 layers, brushed with ghee between each.",
      ingredients: ["Coconut milk", "Egg yolks", "Sugar", "Ghee", "Nutmeg"],
      taste: "Rich, custardy, faintly caramelized",
      significance: "A Christmas staple in Goan Catholic homes, considered the 'queen of Goan desserts'.",
      whereToTry: "Mum's Kitchen, Panjim",
    },
    {
      slug: "prawn-balchao",
      name: "Prawn Balchão",
      origin: "Goan-Portuguese pickle tradition",
      image: img("prawn-balchao", 1000, 800),
      description:
        "A sharp, sweet-sour prawn pickle-curry cooked down with vinegar and dried red chillies, meant to keep for weeks — originally a way to preserve seafood.",
      ingredients: ["Prawns", "Vinegar", "Dried red chillies", "Onion", "Jaggery"],
      taste: "Sharp, sweet, sour, and hot all at once",
      significance: "One of several Goan pickle-curries developed to preserve the day's catch before refrigeration.",
      whereToTry: "Viva Panjim",
    },
  ],
  gallery: [
    { image: img("goa-gal-1", 900, 1200), category: "Nature", caption: "Baga Beach at sunset", tall: true },
    { image: img("goa-gal-2", 900, 700), category: "Architecture", caption: "Basilica of Bom Jesus facade" },
    { image: img("goa-gal-3", 900, 1100), category: "Food", caption: "Goan fish curry and rice" },
    { image: img("goa-gal-4", 900, 700), category: "Attractions", caption: "Fort Aguada lighthouse" },
    { image: img("goa-gal-5", 900, 1300), category: "Nature", caption: "Dudhsagar Falls in full flow", tall: true },
    { image: img("goa-gal-6", 900, 700), category: "Culture", caption: "Carnival parade float" },
    { image: img("goa-gal-7", 900, 900), category: "Markets", caption: "Anjuna flea market stalls" },
  ],
  hotels: [
    {
      slug: "backpacker-panjim-hostel",
      name: "Backpacker Panjim Hostel",
      tier: "Budget",
      pricePerNight: 900,
      rating: 4.2,
      image: img("goa-hotel-budget", 900, 700),
      lat: 15.4989,
      lng: 73.8278,
    },
    {
      slug: "taj-fort-aguada",
      name: "Taj Fort Aguada Resort",
      tier: "Luxury",
      pricePerNight: 18000,
      rating: 4.8,
      image: img("goa-hotel-luxury", 900, 700),
      lat: 15.4936,
      lng: 73.7719,
    },
    {
      slug: "calangute-beach-resort",
      name: "Calangute Beach Resort",
      tier: "Mid-range",
      pricePerNight: 4500,
      rating: 4.4,
      image: img("goa-hotel-midrange", 900, 700),
      lat: 15.5439,
      lng: 73.7553,
    },
  ],
  restaurants: [
    {
      slug: "britto-baga",
      name: "Britto's",
      cuisine: "Goan Seafood",
      priceLevel: 3,
      rating: 4.5,
      image: img("goa-resto-britto", 900, 700),
      lat: 15.5556,
      lng: 73.7513,
    },
    {
      slug: "viva-panjim",
      name: "Viva Panjim",
      cuisine: "Goan",
      priceLevel: 2,
      rating: 4.6,
      image: img("goa-resto-viva", 900, 700),
      lat: 15.4997,
      lng: 73.8283,
    },
    {
      slug: "curlies-anjuna",
      name: "Curlie's",
      cuisine: "Beach Shack",
      priceLevel: 2,
      rating: 4.3,
      image: img("goa-resto-curlies", 900, 700),
      lat: 15.5729,
      lng: 73.7398,
    },
  ],
  languageGuide: {
    primary: "Konkani",
    alsoCommon: ["English", "Marathi", "Hindi"],
    phrases: [
      { phrase: "Dev Boro Dis Dium", translation: "Good day", phonetic: "dev boh-roh dees dee-oom" },
      { phrase: "Deu Borem Korum", translation: "Thank you", phonetic: "deh-oo boh-rem koh-room" },
      { phrase: "Kitem Mol?", translation: "How much does it cost?", phonetic: "kee-tem mohl" },
      { phrase: "Khoim Asa?", translation: "Where is it?", phonetic: "khoim ah-sah" },
      { phrase: "Voi / Na", translation: "Yes / No", phonetic: "voy / nah" },
    ],
  },
  transport: [
    {
      mode: "Flight",
      from: "Mumbai",
      approxTime: "1 hr",
      approxCost: "₹2,500–₹6,000",
      detail: "Frequent flights into Dabolim (Goa) Airport or Manohar International Airport (Mopa).",
    },
    {
      mode: "Train",
      from: "Mumbai",
      approxTime: "10–12 hrs",
      approxCost: "₹500–₹2,000",
      detail: "Konkan Railway overnight trains to Madgaon or Thivim stations.",
    },
    {
      mode: "Bus",
      from: "Mumbai",
      approxTime: "12–14 hrs",
      approxCost: "₹800–₹1,800",
      detail: "Overnight AC sleeper buses run daily along the Konkan coast.",
    },
    {
      mode: "Car",
      from: "Mumbai",
      approxTime: "10–11 hrs",
      approxCost: "₹6,000–₹9,000 (cab, one-way)",
      detail: "Via NH66 along the coast — a scenic but long drive.",
    },
  ],
  weather: {
    tempC: 29,
    feelsLikeC: 32,
    humidity: 68,
    windKmh: 14,
    condition: "Sunny",
    forecast: [
      { label: "Today", tempC: 29, condition: "Sunny" },
      { label: "Tomorrow", tempC: 30, condition: "Sunny" },
      { label: "Wed", tempC: 28, condition: "Partly Cloudy" },
      { label: "Thu", tempC: 29, condition: "Sunny" },
      { label: "Fri", tempC: 29, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Peak season — dry, sunny, warm sea." },
    { month: "Feb", score: 2, note: "Still dry and pleasant, slightly less crowded." },
    { month: "Mar", score: 1, note: "Warming up, good beach weather." },
    { month: "Apr", score: 1, note: "Hot and humid before monsoon." },
    { month: "May", score: 0, note: "Very hot and humid, pre-monsoon buildup." },
    { month: "Jun", score: 0, note: "Monsoon begins — rough seas, many shacks close." },
    { month: "Jul", score: 0, note: "Peak monsoon, heavy rain." },
    { month: "Aug", score: 0, note: "Monsoon continues, best avoided for beaches." },
    { month: "Sep", score: 1, note: "Monsoon tapering, lush green landscape." },
    { month: "Oct", score: 2, note: "Shacks reopen, waterfalls at their fullest." },
    { month: "Nov", score: 2, note: "Season kicks off properly, warm and dry." },
    { month: "Dec", score: 2, note: "Peak season — Christmas, New Year, biggest crowds." },
  ],
  festivals: [
    {
      slug: "goa-carnival",
      name: "Goa Carnival",
      dateLabel: "February / March",
      image: img("goa-fest-carnival", 900, 700),
      description:
        "Four days of parades, floats and street parties before Lent — the only state-sanctioned Carnival in India, centered on Panjim.",
    },
    {
      slug: "sunburn-festival",
      name: "Sunburn Festival",
      dateLabel: "December",
      image: img("goa-fest-sunburn", 900, 700),
      description:
        "One of Asia's largest EDM festivals, drawing international DJs and hundreds of thousands of attendees to Vagator.",
    },
    {
      slug: "shigmo",
      name: "Shigmo",
      dateLabel: "March",
      image: img("goa-fest-shigmo", 900, 700),
      description:
        "Goa's spring festival — colourful processions, folk dance and float parades held across towns and villages statewide.",
    },
  ],
  shopping: [
    {
      category: "Spices",
      item: "Goan spice blends & cashew feni",
      image: img("goa-shop-spices", 900, 700),
      priceRange: "₹150–₹1,000",
      whereToBuy: "Mapusa Market, spice plantations",
      bargainingTip: "Spice plantation tours often include tastings — buy there rather than tourist-strip stalls.",
    },
    {
      category: "Textiles",
      item: "Beachwear & handloom cotton",
      image: img("goa-shop-textiles", 900, 700),
      priceRange: "₹200–₹1,500",
      whereToBuy: "Anjuna Flea Market, Calangute",
      bargainingTip: "Wednesday flea market prices drop noticeably as evening approaches.",
    },
    {
      category: "Handicrafts",
      item: "Azulejo-style tiles & wood carvings",
      image: img("goa-shop-crafts", 900, 700),
      priceRange: "₹300–₹4,000",
      whereToBuy: "Fontainhas quarter, Panjim",
      bargainingTip: "Government emporiums have fixed, fair prices if you'd rather skip haggling.",
    },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Swim only at beaches with lifeguard flags — currents can be strong, especially in monsoon season.",
      "Avoid renting scooters without a valid license and helmet — checks are common.",
      "Agree on taxi/rickshaw fares upfront, or use a metered app.",
      "Stick to licensed water-sports operators.",
      "Be cautious with drinks at unlicensed beach parties.",
      "Carry a copy of your ID; police checks near nightlife areas are routine.",
    ],
  },
};

export const manali: Destination = {
  slug: "manali",
  name: "Manali",
  tagline: "Gateway to the Himalayas",
  region: "Himachal Pradesh",
  country: "India",
  rating: 4.7,
  heroImage: img("manali-hero", 1800, 1100),
  cardImage: img("manali-card", 900, 1100),
  tags: ["Mountains", "Adventure", "Nature"],
  bestTime: "Mar – Jun, Oct – Feb",
  center: { lat: 32.2432, lng: 77.1892 },
  quickFacts: { weather: "12°C", budget: "₹₹", language: "Hindi", stay: "4–6 Days" },
  intro:
    "Manali sits where the Beas River valley narrows into the high Himalaya, a former trading stop on the old route to Ladakh that's become India's most popular mountain getaway. Snow-capped peaks, pine-covered slopes, and a steady flow of adventure travel — paragliding, skiing, river rafting — sit alongside apple orchards and Hadimba's centuries-old cedar-wood temple.",
  didYouKnow: [
    "Old Manali predates the modern town — its stone-and-wood houses and the Manu Temple are believed to mark the spot where the sage Manu is said to have recreated human life after a great flood.",
    "Rohtang Pass, at over 3,900 metres, was historically the gateway between Kullu Valley and Lahaul-Spiti — now regulated by permit due to heavy tourist traffic.",
    "The Hadimba Temple's wooden tower-style architecture is unique in the region and dates to 1553.",
    "Solang Valley converts into a full ski resort each winter, one of the few in India accessible without technical mountaineering.",
    "Manali is named after the sage Manu, considered the Himalayan equivalent of Noah in Hindu tradition.",
  ],
  attractions: [
    {
      slug: "hadimba-temple",
      name: "Hadimba Devi Temple",
      category: "Religious",
      rating: 4.6,
      image: img("hadimba-temple", 1200, 900),
      duration: "45 minutes",
      ticket: "Free",
      hours: "8:00 AM – 6:00 PM",
      bestTime: "Morning, in the cedar forest light",
      about:
        "A wooden cave-temple built in 1553, dedicated to Hadimba, wife of Bhima from the Mahabharata. Set inside a dense cedar forest, its pagoda-style tower is unlike typical North Indian temple architecture.",
      architecture:
        "A four-tiered wooden tower over a natural cave shrine, with intricately carved wooden doorways — an unusual Himalayan style distinct from stone temples elsewhere in India.",
      location: "Old Manali, Dhungri Forest",
      lat: 32.2468,
      lng: 77.1706,
    },
    {
      slug: "solang-valley",
      name: "Solang Valley",
      category: "Adventure",
      rating: 4.7,
      image: img("solang-valley", 1200, 900),
      duration: "Half day",
      ticket: "Free entry (activities priced separately)",
      hours: "9:00 AM – 5:00 PM",
      bestTime: "Winter for skiing, summer for paragliding",
      about:
        "A glacial valley 14km from Manali that turns into a full adventure-sports hub — paragliding and zorbing in summer, skiing and snowboarding once the winter snow settles in.",
      architecture: "N/A — open valley with seasonal sports infrastructure.",
      location: "Solang, 14km from Manali",
      lat: 32.3181,
      lng: 77.1571,
    },
    {
      slug: "rohtang-pass",
      name: "Rohtang Pass",
      category: "Nature",
      rating: 4.5,
      image: img("rohtang-pass", 1200, 900),
      duration: "Full day (with travel)",
      ticket: "Permit required, ~₹550 per person",
      hours: "Open May–Nov (snow-dependent, permit-limited daily entries)",
      bestTime: "Early morning departure to beat traffic and afternoon fog",
      about:
        "A high mountain pass at 3,978m connecting the Kullu Valley to Lahaul-Spiti, with snow visible even in summer. Entry is capped daily via permit to manage the heavy tourist load.",
      architecture: "N/A — high-altitude mountain pass.",
      location: "51km from Manali, on the Leh–Manali Highway",
      lat: 32.3730,
      lng: 77.2481,
    },
    {
      slug: "old-manali",
      name: "Old Manali",
      category: "Village",
      rating: 4.6,
      image: img("old-manali", 1200, 900),
      duration: "2–3 hours",
      ticket: "Free",
      hours: "Open 24 hours",
      bestTime: "Evening, for the café and market scene",
      about:
        "A quieter, older settlement across the river from the main town — narrow lanes, apple orchards, wood-and-stone houses, and a backpacker café scene that's grown up around the Manu Temple.",
      architecture: "Traditional Himachali wood-and-stone houses with slate roofing.",
      location: "Across the Manalsu River from central Manali",
      lat: 32.2517,
      lng: 77.1691,
    },
    {
      slug: "jogini-waterfall",
      name: "Jogini Waterfall",
      category: "Nature",
      rating: 4.4,
      image: img("jogini-falls", 1200, 900),
      duration: "2 hours (round-trip hike)",
      ticket: "Free",
      hours: "Daylight hours",
      bestTime: "Post-monsoon for full flow, early morning for fewer crowds",
      about:
        "A moderate hike above Vashisht village leads to this multi-tiered waterfall, popular with travelers based in Old Manali looking for a half-day trek without technical difficulty.",
      architecture: "N/A — natural waterfall reached via forest trail.",
      location: "Above Vashisht village",
      lat: 32.2611,
      lng: 77.1917,
    },
  ],
  history: [
    {
      year: "Ancient",
      title: "The legend of Manu",
      description:
        "Local tradition holds that the sage Manu stepped ashore here after a great flood and recreated human life — giving the town its name and the Manu Temple in Old Manali its significance.",
    },
    {
      year: "1553",
      title: "Hadimba Temple is built",
      description:
        "Raja Bahadur Singh commissions the distinctive wooden temple dedicated to Hadimba, still standing in its original cedar-forest setting.",
    },
    {
      year: "19th century",
      title: "British hill station era",
      description:
        "British colonists develop Manali as a summer retreat and introduce apple cultivation, which becomes central to the valley's economy.",
    },
    {
      year: "1960s–70s",
      title: "The hippie trail",
      description:
        "Manali becomes a stop on the overland hippie trail through Asia, seeding the backpacker culture still visible in Old Manali's café scene.",
    },
    {
      year: "1989",
      title: "Rohtang Pass opens further tourism",
      description:
        "Improved road access to Rohtang Pass turns Manali into a gateway for Lahaul-Spiti and Ladakh-bound travelers.",
    },
    {
      year: "Today",
      title: "Modern Manali",
      description:
        "A year-round adventure-tourism hub — skiing in winter, paragliding and trekking in summer — while Old Manali retains its slower, orchard-town character.",
    },
  ],
  culture: [
    {
      slug: "pahari-culture",
      title: "Pahari Traditions",
      category: "Tradition",
      image: img("manali-pahari", 900, 1100),
      description:
        "Himachali hill culture centers on village deities (devta), community festivals, and distinctive wood-and-stone architecture built to withstand heavy snow.",
    },
    {
      slug: "himachali-cap",
      title: "Himachali Cap & Shawls",
      category: "Clothing",
      image: img("manali-cap", 900, 1100),
      description:
        "The green-and-grey Kullu cap and hand-woven pashmina shawls are everyday wear here, not costume — Kullu's weaving cooperatives are centuries old.",
    },
    {
      slug: "kullu-dussehra",
      title: "Kullu Dussehra",
      category: "Festival",
      image: img("manali-dussehra", 900, 1100),
      description:
        "A week-long festival where village deities are carried in procession to Kullu to pay respects to Raghunath — one of Himachal's largest gatherings.",
    },
    {
      slug: "himachali-nati",
      title: "Nati Dance",
      category: "Dance",
      image: img("manali-nati", 900, 1100),
      description:
        "A circular folk dance performed at festivals and weddings across the Kullu-Manali region, recognized by the Guinness World Records for its scale during Kullu Dussehra.",
    },
  ],
  food: [
    {
      slug: "siddu",
      name: "Siddu",
      origin: "Himachali home cooking",
      image: img("siddu", 1000, 800),
      description:
        "A steamed, stuffed wheat bread — filled with poppy seed paste or minced meat — served with ghee and a side of mint or walnut chutney. Himachal's answer to the dumpling.",
      ingredients: ["Wheat flour", "Poppy seeds or minced meat", "Ghee", "Yeast"],
      taste: "Soft, mildly nutty, savory",
      significance: "A winter staple across Himachali hill villages, traditionally slow-steamed over a wood fire.",
      whereToTry: "Local dhabas in Old Manali",
    },
    {
      slug: "trout-fish",
      name: "Himalayan Trout",
      origin: "Beas River valley",
      image: img("trout", 1000, 800),
      description:
        "Freshwater trout, farmed in the cold streams around Manali, pan-fried or grilled with local herbs — a rare fresh-fish option this high in the mountains.",
      ingredients: ["Trout", "Garlic", "Butter", "Local herbs"],
      taste: "Delicate, buttery, mildly earthy",
      significance: "Trout farming was introduced by the British and remains a local specialty.",
      whereToTry: "Johnson's Cafe, Manali",
    },
    {
      slug: "dham",
      name: "Himachali Dham",
      origin: "Ceremonial Himachali cuisine",
      image: img("dham", 1000, 800),
      description:
        "A multi-course vegetarian feast traditionally served at weddings and festivals, cooked by specialist chefs called 'botis' in large brass vessels.",
      ingredients: ["Rice", "Rajma or black chana", "Curd-based curries", "Ghee"],
      taste: "Rich, mildly spiced, comforting",
      significance: "Reserved for celebrations — considered the definitive expression of Himachali hospitality.",
      whereToTry: "Book ahead at heritage guesthouses; rarely on regular menus",
    },
    {
      slug: "apple-cider",
      name: "Local Apple Cider & Chutney",
      origin: "Kullu Valley orchards",
      image: img("apple-cider", 1000, 800),
      description:
        "Manali sits in one of India's main apple-growing belts — fresh cider, jams and chutneys are sold roadside straight from orchard families each autumn.",
      ingredients: ["Apples", "Sugar", "Spices"],
      taste: "Sweet-tart, lightly spiced",
      significance: "Apple farming, introduced under British rule, remains the valley's main cash crop.",
      whereToTry: "Roadside orchard stalls between Manali and Naggar",
    },
  ],
  gallery: [
    { image: img("manali-gal-1", 900, 1200), category: "Nature", caption: "Snow-dusted pines near Solang Valley", tall: true },
    { image: img("manali-gal-2", 900, 700), category: "Architecture", caption: "Hadimba Temple's wooden tower" },
    { image: img("manali-gal-3", 900, 1100), category: "Adventure", caption: "Paragliding over Solang" },
    { image: img("manali-gal-4", 900, 700), category: "Nature", caption: "Rohtang Pass in early summer" },
    { image: img("manali-gal-5", 900, 1300), category: "Culture", caption: "Nati dancers at Kullu Dussehra", tall: true },
    { image: img("manali-gal-6", 900, 700), category: "Food", caption: "Siddu served with ghee" },
    { image: img("manali-gal-7", 900, 900), category: "Nature", caption: "Old Manali orchards in autumn" },
  ],
  hotels: [
    {
      slug: "zostel-manali",
      name: "Zostel Manali",
      tier: "Budget",
      pricePerNight: 1200,
      rating: 4.4,
      image: img("manali-hotel-budget", 900, 700),
      lat: 32.2517,
      lng: 77.1691,
    },
    {
      slug: "span-resort",
      name: "Span Resort & Spa",
      tier: "Luxury",
      pricePerNight: 12000,
      rating: 4.7,
      image: img("manali-hotel-luxury", 900, 700),
      lat: 32.2100,
      lng: 77.1600,
    },
    {
      slug: "snow-valley-resorts",
      name: "Snow Valley Resorts",
      tier: "Mid-range",
      pricePerNight: 4800,
      rating: 4.5,
      image: img("manali-hotel-midrange", 900, 700),
      lat: 32.2396,
      lng: 77.1887,
    },
  ],
  restaurants: [
    {
      slug: "johnsons-cafe",
      name: "Johnson's Cafe",
      cuisine: "Continental",
      priceLevel: 3,
      rating: 4.5,
      image: img("manali-resto-johnsons", 900, 700),
      lat: 32.2404,
      lng: 77.1898,
    },
    {
      slug: "cafe-1947",
      name: "Cafe 1947",
      cuisine: "Multi-cuisine",
      priceLevel: 2,
      rating: 4.4,
      image: img("manali-resto-1947", 900, 700),
      lat: 32.2513,
      lng: 77.1698,
    },
    {
      slug: "renaissance-restaurant",
      name: "Renaissance Restaurant",
      cuisine: "Himachali",
      priceLevel: 2,
      rating: 4.3,
      image: img("manali-resto-renaissance", 900, 700),
      lat: 32.2432,
      lng: 77.1892,
    },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["Pahari (Kullvi dialect)", "English"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nə-məs-teɪ" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhən-yə-vaad" },
      { phrase: "Kitne ka hai?", translation: "How much is this?", phonetic: "kit-ne kaa hai" },
      { phrase: "Kitni door hai?", translation: "How far is it?", phonetic: "kit-nee dhoor hai" },
      { phrase: "Thanda bahut hai", translation: "It's very cold", phonetic: "thən-dah bə-hoot hai" },
    ],
  },
  transport: [
    {
      mode: "Flight",
      from: "Delhi",
      approxTime: "1 hr to Bhuntar (Kullu) + 50 min drive",
      approxCost: "₹4,000–₹8,000",
      detail: "Fly into Kullu-Manali Airport (Bhuntar), then a short drive to Manali.",
    },
    {
      mode: "Bus",
      from: "Delhi",
      approxTime: "12–14 hrs",
      approxCost: "₹800–₹2,200",
      detail: "Overnight Volvo/HRTC buses run daily from Delhi's ISBT.",
    },
    {
      mode: "Train",
      from: "Delhi",
      approxTime: "10 hrs to Chandigarh + 7 hr drive",
      approxCost: "₹500–₹1,500 (train) + cab",
      detail: "Nearest railhead is Chandigarh or Ambala; the rest is by road.",
    },
    {
      mode: "Car",
      from: "Delhi",
      approxTime: "12–13 hrs",
      approxCost: "₹8,000–₹12,000 (cab, one-way)",
      detail: "Via NH44 and NH3, a long but scenic mountain drive.",
    },
  ],
  weather: {
    tempC: 12,
    feelsLikeC: 9,
    humidity: 55,
    windKmh: 10,
    condition: "Partly Cloudy",
    forecast: [
      { label: "Today", tempC: 12, condition: "Partly Cloudy" },
      { label: "Tomorrow", tempC: 10, condition: "Cloudy" },
      { label: "Wed", tempC: 8, condition: "Rainy" },
      { label: "Thu", tempC: 11, condition: "Partly Cloudy" },
      { label: "Fri", tempC: 13, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 1, note: "Snow-covered, good for winter sports, very cold." },
    { month: "Feb", score: 1, note: "Still snowy, ski season continues." },
    { month: "Mar", score: 2, note: "Snow melting, valley turning green." },
    { month: "Apr", score: 2, note: "Pleasant spring weather, orchards blooming." },
    { month: "May", score: 2, note: "Warm days, Rohtang Pass reopens." },
    { month: "Jun", score: 2, note: "Peak summer season, cool relief from plains heat." },
    { month: "Jul", score: 0, note: "Monsoon — landslide risk on mountain roads." },
    { month: "Aug", score: 0, note: "Heavy monsoon rain continues." },
    { month: "Sep", score: 1, note: "Monsoon tapering, roads improving." },
    { month: "Oct", score: 2, note: "Clear skies, crisp air, apple harvest." },
    { month: "Nov", score: 1, note: "Getting cold, first snow possible." },
    { month: "Dec", score: 1, note: "Snowfall begins, winter sports season starts." },
  ],
  festivals: [
    {
      slug: "kullu-dussehra",
      name: "Kullu Dussehra",
      dateLabel: "October",
      image: img("manali-fest-dussehra", 900, 700),
      description:
        "A week-long celebration where hundreds of local deities are carried in procession to Kullu — one of Himachal's largest cultural gatherings.",
    },
    {
      slug: "winter-carnival",
      name: "Manali Winter Carnival",
      dateLabel: "January",
      image: img("manali-fest-winter", 900, 700),
      description:
        "A festival of skiing competitions, cultural performances and bonfires marking the peak of the snow season.",
    },
    {
      slug: "hadimba-fair",
      name: "Hadimba Devi Fair",
      dateLabel: "May",
      image: img("manali-fest-hadimba", 900, 700),
      description: "A local fair held at the Hadimba Temple with folk music, dance and traditional food stalls.",
    },
  ],
  shopping: [
    {
      category: "Textiles",
      item: "Kullu shawls & pashmina",
      image: img("manali-shop-shawls", 900, 700),
      priceRange: "₹500–₹5,000",
      whereToBuy: "Mall Road, Kullu weaving cooperatives",
      bargainingTip: "Cooperative-run shops have fixed, fair prices and support local weavers directly.",
    },
    {
      category: "Handicrafts",
      item: "Himachali caps & wood carvings",
      image: img("manali-shop-caps", 900, 700),
      priceRange: "₹150–₹1,200",
      whereToBuy: "Mall Road, Old Manali market",
      bargainingTip: "Prices are fairly fixed on Mall Road; more room to negotiate in Old Manali stalls.",
    },
    {
      category: "Food",
      item: "Apple products & local honey",
      image: img("manali-shop-apple", 900, 700),
      priceRange: "₹100–₹800",
      whereToBuy: "Roadside orchard stalls, Mall Road",
      bargainingTip: "Buy directly from orchard stalls outside town for better prices and freshness.",
    },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Acclimatize before heading to high-altitude spots like Rohtang Pass — altitude sickness is real above 3,000m.",
      "Check road conditions before mountain drives, especially in monsoon (landslides) and winter (snow closures).",
      "Carry warm layers even in summer — mountain weather changes fast.",
      "Use registered adventure-sports operators only (paragliding, rafting).",
      "Rohtang Pass requires a permit — arrange this in advance in Manali.",
      "Mobile network can be patchy beyond the main town; download offline maps.",
    ],
  },
};

export const varanasi: Destination = {
  slug: "varanasi",
  name: "Varanasi",
  tagline: "The Eternal City",
  region: "Uttar Pradesh",
  country: "India",
  rating: 4.7,
  heroImage: img("varanasi-hero", 1800, 1100),
  cardImage: img("varanasi-card", 900, 1100),
  tags: ["Spiritual", "Heritage", "Ganges"],
  bestTime: "Oct – Mar",
  center: { lat: 25.3176, lng: 82.9739 },
  quickFacts: { weather: "27°C", budget: "₹", language: "Hindi", stay: "2–3 Days" },
  intro:
    "Varanasi is older than memory — among the oldest continuously inhabited cities on earth, and Hinduism's holiest. Life and death share the same riverbank here: pilgrims bathe at dawn where cremation pyres burn through the night, and the eighty-odd stone ghats that line the Ganges have watched this ritual repeat for over three thousand years.",
  didYouKnow: [
    "Varanasi is considered one of the oldest continuously inhabited cities in the world, with settlement dating back over 3,000 years.",
    "Mark Twain wrote that Varanasi is 'older than history, older than tradition, older even than legend.'",
    "Manikarnika Ghat cremates bodies around the clock, 365 days a year — Hindus believe dying here grants moksha, liberation from the cycle of rebirth.",
    "The Ganga Aarti at Dashashwamedh Ghat is performed every single evening without exception, rain or shine.",
    "Varanasi is also the birthplace of Banarasi silk sarees, woven with real gold and silver thread since the Mughal era.",
    "The Buddha delivered his first sermon at nearby Sarnath, just 10km from Varanasi, making the city significant to Buddhists too.",
  ],
  attractions: [
    {
      slug: "kashi-vishwanath-temple",
      name: "Kashi Vishwanath Temple",
      category: "Religious",
      rating: 4.8,
      image: img("kashi-vishwanath", 1200, 900),
      duration: "1–2 hours (including queue)",
      ticket: "Free (express darshan ticket available, ~₹300)",
      hours: "3:00 AM – 11:00 PM",
      bestTime: "Early morning Mangala Aarti (3:30 AM) for the least crowded darshan",
      about:
        "One of the twelve Jyotirlingas of Shiva, and the spiritual center of Varanasi. The current structure dates to 1780, rebuilt by Ahilyabai Holkar after earlier temples were destroyed; a new pedestrian corridor now connects it directly to the Ganges.",
      architecture:
        "North Indian temple style with a gold-plated spire (donated by Maharaja Ranjit Singh), rebuilt in sandstone after Mughal-era demolitions.",
      location: "Vishwanath Gali, near Dashashwamedh Ghat",
      lat: 25.3109,
      lng: 83.0107,
    },
    {
      slug: "dashashwamedh-ghat",
      name: "Dashashwamedh Ghat",
      category: "Ghat",
      rating: 4.8,
      image: img("dashashwamedh-ghat", 1200, 900),
      duration: "1.5 hours (for the evening Aarti)",
      ticket: "Free (boat viewing ~₹200–500)",
      hours: "Open 24 hours; Ganga Aarti at sunset",
      bestTime: "Sunset, for the Ganga Aarti ceremony",
      about:
        "Varanasi's most iconic ghat, believed to be where Brahma sacrificed ten horses in a ritual to welcome Shiva. Every evening, priests perform a synchronized fire ceremony (Ganga Aarti) facing the river, watched by thousands from the steps and from boats.",
      architecture:
        "A wide stone stairway descending to the Ganges, backed by temples and pilgrim rest-houses built over centuries by different royal patrons.",
      location: "Central Varanasi, on the Ganges",
      lat: 25.3069,
      lng: 83.0107,
    },
    {
      slug: "sarnath",
      name: "Sarnath",
      category: "Historical",
      rating: 4.6,
      image: img("sarnath", 1200, 900),
      duration: "2–3 hours",
      ticket: "₹25 (Indians) / ₹300 (Foreigners)",
      hours: "6:00 AM – 6:00 PM (Wed–Mon)",
      bestTime: "Morning, to avoid midday heat",
      about:
        "The site where the Buddha gave his first sermon after attaining enlightenment, marked today by the towering Dhamek Stupa and ruins of ancient monasteries. One of Buddhism's four most sacred pilgrimage sites.",
      architecture:
        "The Dhamek Stupa is a 43.6m cylindrical brick-and-stone tower dating to the Ashokan era (3rd century BCE), with later Gupta-period additions.",
      location: "10km northeast of central Varanasi",
      lat: 25.3811,
      lng: 83.0244,
    },
    {
      slug: "assi-ghat",
      name: "Assi Ghat",
      category: "Ghat",
      rating: 4.6,
      image: img("assi-ghat", 1200, 900),
      duration: "1 hour",
      ticket: "Free",
      hours: "Open 24 hours",
      bestTime: "Sunrise, for yoga sessions and the morning Subah-e-Banaras ceremony",
      about:
        "The southernmost of Varanasi's major ghats, where the Assi River meets the Ganges. Quieter and more residential than Dashashwamedh, popular with students, yoga practitioners and early risers.",
      architecture: "A broad open ghat with fewer temple structures than the central ghats, backed by cafes and guesthouses.",
      location: "Southern end of the ghat chain",
      lat: 25.2887,
      lng: 83.0047,
    },
    {
      slug: "manikarnika-ghat",
      name: "Manikarnika Ghat",
      category: "Ghat",
      rating: 4.5,
      image: img("manikarnika-ghat", 1200, 900),
      duration: "30–45 minutes (respectful viewing, ideally with a guide)",
      ticket: "Free — donations to the eternal flame are customary, but be wary of scams",
      hours: "Open 24 hours",
      bestTime: "Any time — cremations continue continuously",
      about:
        "The primary cremation ghat in Varanasi, where funeral pyres have burned continuously for centuries. Considered the most auspicious place in Hinduism to be cremated. Visitors should observe respectfully from a distance and avoid photography.",
      architecture: "A working ghat with wood-stacking platforms and a sacred eternal flame said to have burned for millennia.",
      location: "Central ghats, north of Dashashwamedh",
      lat: 25.3129,
      lng: 83.0146,
    },
  ],
  history: [
    {
      year: "c. 1200 BCE",
      title: "Early settlement",
      description:
        "Archaeological evidence places continuous settlement at Varanasi back to at least the early Iron Age, among the oldest of any living city.",
    },
    {
      year: "6th century BCE",
      title: "The Buddha at Sarnath",
      description:
        "Siddhartha Gautama delivers his first sermon at nearby Sarnath after attaining enlightenment, founding the Buddhist Sangha.",
    },
    {
      year: "12th century CE",
      title: "Temple destructions begin",
      description:
        "Successive invasions, including by Qutb-ud-din Aibak, destroy earlier iterations of the Kashi Vishwanath Temple over several centuries.",
    },
    {
      year: "1669",
      title: "Aurangzeb's demolition",
      description:
        "Mughal emperor Aurangzeb demolishes the temple again and builds the Gyanvapi Mosque on part of the site — a source of ongoing dispute today.",
    },
    {
      year: "1780",
      title: "The current temple is built",
      description:
        "Maharani Ahilyabai Holkar of Indore rebuilds Kashi Vishwanath Temple in its current form, adjacent to the mosque site.",
    },
    {
      year: "Today",
      title: "Modern Varanasi",
      description:
        "A 2019 corridor project connects the temple directly to the Ganges, drawing record pilgrim numbers while the city's ghats and narrow lanes retain their centuries-old rhythm.",
    },
  ],
  culture: [
    {
      slug: "ganga-aarti",
      title: "Ganga Aarti",
      category: "Ritual",
      image: img("varanasi-aarti", 900, 1100),
      description:
        "A nightly fire ceremony performed by priests at Dashashwamedh Ghat, offering flame, incense and chant to the river goddess Ganga — performed without fail every single evening.",
    },
    {
      slug: "banarasi-silk",
      title: "Banarasi Silk Weaving",
      category: "Handicraft",
      image: img("varanasi-silk", 900, 1100),
      description:
        "A centuries-old weaving tradition producing sarees with intricate gold and silver zari thread, historically patronized by Mughal courts and still hand-loomed in the city's old quarters.",
    },
    {
      slug: "banaras-gharana",
      title: "Banaras Gharana",
      category: "Music",
      image: img("varanasi-music", 900, 1100),
      description:
        "A distinct classical music tradition centered on the tabla and thumri vocal style, with Varanasi as one of Hindustani classical music's most important historic centers.",
    },
    {
      slug: "dev-deepawali",
      title: "Dev Deepawali",
      category: "Festival",
      image: img("varanasi-deepawali", 900, 1100),
      description:
        "The 'Diwali of the Gods' — millions of oil lamps line every ghat fifteen days after Diwali, marking the day the gods are said to descend to bathe in the Ganges.",
    },
  ],
  food: [
    {
      slug: "banarasi-paan",
      name: "Banarasi Paan",
      origin: "Varanasi street tradition",
      image: img("banarasi-paan", 1000, 800),
      description:
        "A betel-leaf preparation stuffed with areca nut, lime paste, and sweet or spiced fillings — a Varanasi institution, chewed as a post-meal digestive and palate cleanser.",
      ingredients: ["Betel leaf", "Areca nut", "Lime paste", "Gulkand or spices"],
      taste: "Sweet, aromatic, mildly astringent",
      significance: "So central to local identity that 'Banarasi paan' is a recognized geographical-indication product.",
      whereToTry: "Keshav Tambul Bhandar, Godowlia",
    },
    {
      slug: "kachori-sabzi",
      name: "Kachori Sabzi",
      origin: "Varanasi breakfast tradition",
      image: img("varanasi-kachori", 1000, 800),
      description:
        "Deep-fried lentil-stuffed kachoris served with a spiced potato curry — the definitive Varanasi breakfast, eaten fresh off the griddle at street stalls from early morning.",
      ingredients: ["Refined flour", "Urad dal", "Potatoes", "Whole spices"],
      taste: "Savory, mildly spiced, filling",
      significance: "A daily ritual for locals — certain stalls have served the same recipe for generations.",
      whereToTry: "Kachori Gali, near Vishwanath Temple",
    },
    {
      slug: "banarasi-thandai",
      name: "Banarasi Thandai",
      origin: "Varanasi religious and festive tradition",
      image: img("thandai", 1000, 800),
      description:
        "A chilled, spiced milk drink blended with almonds, fennel, and rose — closely associated with Shaivite tradition and often served during festivals like Mahashivratri and Holi.",
      ingredients: ["Milk", "Almonds", "Fennel seeds", "Rose petals", "Saffron"],
      taste: "Sweet, floral, richly spiced",
      significance: "Traditionally linked to Lord Shiva; some versions include bhang (cannabis) on specific festival days.",
      whereToTry: "Blue Lassi Shop area, Old City",
    },
    {
      slug: "malaiyyo",
      name: "Malaiyyo",
      origin: "Winter-only Varanasi sweet",
      image: img("malaiyyo", 1000, 800),
      description:
        "A cloud-like, saffron-dusted milk foam dessert made only in winter, when the cold morning dew is traditionally used to help set the delicate froth overnight.",
      ingredients: ["Milk", "Saffron", "Pistachios", "Sugar"],
      taste: "Light, airy, delicately sweet",
      significance: "A strictly seasonal specialty — available only November through February.",
      whereToTry: "Street stalls near Chowk, mornings only",
    },
  ],
  gallery: [
    { image: img("varanasi-gal-1", 900, 1200), category: "Ghats", caption: "Dashashwamedh Ghat at dawn", tall: true },
    { image: img("varanasi-gal-2", 900, 700), category: "Ritual", caption: "Ganga Aarti fire ceremony" },
    { image: img("varanasi-gal-3", 900, 1100), category: "Architecture", caption: "Kashi Vishwanath's gold spire" },
    { image: img("varanasi-gal-4", 900, 700), category: "People", caption: "Boats along the ghats" },
    { image: img("varanasi-gal-5", 900, 1300), category: "Heritage", caption: "Dhamek Stupa at Sarnath", tall: true },
    { image: img("varanasi-gal-6", 900, 700), category: "Food", caption: "Banarasi paan being folded" },
    { image: img("varanasi-gal-7", 900, 900), category: "Culture", caption: "Banarasi silk loom in progress" },
  ],
  hotels: [
    {
      slug: "stops-hostel-varanasi",
      name: "Stops Hostel Varanasi",
      tier: "Budget",
      pricePerNight: 800,
      rating: 4.3,
      image: img("varanasi-hotel-budget", 900, 700),
      lat: 25.3069,
      lng: 83.0090,
    },
    {
      slug: "taj-nadesar-palace",
      name: "Taj Nadesar Palace",
      tier: "Luxury",
      pricePerNight: 16000,
      rating: 4.7,
      image: img("varanasi-hotel-luxury", 900, 700),
      lat: 25.3324,
      lng: 82.9925,
    },
    {
      slug: "ganges-view-hotel",
      name: "Ganges View Hotel",
      tier: "Mid-range",
      pricePerNight: 3800,
      rating: 4.5,
      image: img("varanasi-hotel-midrange", 900, 700),
      lat: 25.2887,
      lng: 83.0055,
    },
  ],
  restaurants: [
    {
      slug: "kashi-chat-bhandar",
      name: "Kashi Chat Bhandar",
      cuisine: "Street Food",
      priceLevel: 1,
      rating: 4.5,
      image: img("varanasi-resto-chat", 900, 700),
      lat: 25.3103,
      lng: 83.0098,
    },
    {
      slug: "blue-lassi-shop",
      name: "Blue Lassi Shop",
      cuisine: "Café",
      priceLevel: 1,
      rating: 4.6,
      image: img("varanasi-resto-lassi", 900, 700),
      lat: 25.3111,
      lng: 83.0089,
    },
    {
      slug: "brown-bread-bakery",
      name: "Brown Bread Bakery",
      cuisine: "Multi-cuisine",
      priceLevel: 2,
      rating: 4.4,
      image: img("varanasi-resto-bakery", 900, 700),
      lat: 25.3095,
      lng: 83.0079,
    },
  ],
  languageGuide: {
    primary: "Hindi",
    alsoCommon: ["Bhojpuri", "English"],
    phrases: [
      { phrase: "Namaste", translation: "Hello", phonetic: "nə-məs-teɪ" },
      { phrase: "Dhanyavaad", translation: "Thank you", phonetic: "dhən-yə-vaad" },
      { phrase: "Ghat kahan hai?", translation: "Where is the ghat?", phonetic: "ghaat kə-haan hai" },
      { phrase: "Kitne ka hai?", translation: "How much is this?", phonetic: "kit-ne kaa hai" },
      { phrase: "Boat kitne mein?", translation: "How much for the boat?", phonetic: "boht kit-ne mein" },
    ],
  },
  transport: [
    {
      mode: "Flight",
      from: "New Delhi",
      approxTime: "1.5 hrs",
      approxCost: "₹3,500–₹7,000",
      detail: "Daily flights into Lal Bahadur Shastri International Airport.",
    },
    {
      mode: "Train",
      from: "New Delhi",
      approxTime: "10–13 hrs",
      approxCost: "₹400–₹2,000",
      detail: "Multiple daily trains, including overnight options, into Varanasi Junction.",
    },
    {
      mode: "Bus",
      from: "Lucknow",
      approxTime: "6–7 hrs",
      approxCost: "₹400–₹900",
      detail: "Regular UPSRTC and private buses connect major nearby cities.",
    },
    {
      mode: "Car",
      from: "Lucknow",
      approxTime: "5–6 hrs",
      approxCost: "₹3,500–₹5,000 (cab, one-way)",
      detail: "Via NH19/NH31, a well-connected route.",
    },
  ],
  weather: {
    tempC: 27,
    feelsLikeC: 29,
    humidity: 52,
    windKmh: 9,
    condition: "Sunny",
    forecast: [
      { label: "Today", tempC: 27, condition: "Sunny" },
      { label: "Tomorrow", tempC: 28, condition: "Sunny" },
      { label: "Wed", tempC: 26, condition: "Partly Cloudy" },
      { label: "Thu", tempC: 27, condition: "Sunny" },
      { label: "Fri", tempC: 29, condition: "Sunny" },
    ],
  },
  bestTimeCalendar: [
    { month: "Jan", score: 2, note: "Cool and pleasant, ideal for ghat walks." },
    { month: "Feb", score: 2, note: "Still cool, comfortable sightseeing weather." },
    { month: "Mar", score: 1, note: "Warming up quickly." },
    { month: "Apr", score: 0, note: "Hot, best avoided for extended walking." },
    { month: "May", score: 0, note: "Peak heat, often above 40°C." },
    { month: "Jun", score: 0, note: "Very hot, monsoon builds late month." },
    { month: "Jul", score: 1, note: "Monsoon — river levels rise, some ghats partly submerged." },
    { month: "Aug", score: 1, note: "Monsoon continues, humid." },
    { month: "Sep", score: 1, note: "Monsoon tapering off." },
    { month: "Oct", score: 2, note: "Post-monsoon, festival season begins." },
    { month: "Nov", score: 2, note: "Dev Deepawali, cool and clear." },
    { month: "Dec", score: 2, note: "Cool, dry, peak pilgrim and tourist season." },
  ],
  festivals: [
    {
      slug: "dev-deepawali",
      name: "Dev Deepawali",
      dateLabel: "November",
      image: img("varanasi-fest-deepawali", 900, 700),
      description:
        "Millions of oil lamps illuminate every ghat fifteen days after Diwali — considered the most spectacular sight in Varanasi's festival calendar.",
    },
    {
      slug: "mahashivratri",
      name: "Mahashivratri",
      dateLabel: "February / March",
      image: img("varanasi-fest-shivratri", 900, 700),
      description:
        "A major festival honoring Shiva, marked by an all-night vigil, processions, and huge crowds at Kashi Vishwanath Temple.",
    },
    {
      slug: "budh-purnima",
      name: "Buddha Purnima",
      dateLabel: "April / May",
      image: img("varanasi-fest-buddha", 900, 700),
      description:
        "Celebrated with particular significance at nearby Sarnath, marking the Buddha's birth, enlightenment, and death.",
    },
  ],
  shopping: [
    {
      category: "Textiles",
      item: "Banarasi silk sarees",
      image: img("varanasi-shop-silk", 900, 700),
      priceRange: "₹2,000–₹50,000+",
      whereToBuy: "Chowk, Vishwanath Gali, government emporiums",
      bargainingTip: "Ask to see the weave against light — genuine zari thread won't tarnish or peel.",
    },
    {
      category: "Handicrafts",
      item: "Brass & copper ritual items",
      image: img("varanasi-shop-brass", 900, 700),
      priceRange: "₹100–₹3,000",
      whereToBuy: "Thatheri Bazaar",
      bargainingTip: "Weight is a good indicator of quality — genuine brass feels notably heavier.",
    },
    {
      category: "Religious items",
      item: "Rudraksha malas & prayer items",
      image: img("varanasi-shop-rudraksha", 900, 700),
      priceRange: "₹100–₹5,000",
      whereToBuy: "Stalls near Kashi Vishwanath Temple",
      bargainingTip: "Prices scale steeply with bead size and 'mukhi' count — ask for a certificate on expensive pieces.",
    },
  ],
  safety: {
    emergency: { police: "100", ambulance: "108", fire: "101" },
    tips: [
      "Be respectful and avoid photography at Manikarnika Ghat — it's an active cremation site, not a tourist attraction.",
      "Agree on boat ride prices before boarding, and expect heavy touting near the main ghats.",
      "The old city's lanes are narrow and easy to get lost in — keep your accommodation's location saved.",
      "Drink only bottled or well-filtered water.",
      "Cows, motorbikes and pilgrims share the same narrow lanes — watch your step, literally.",
      "Dress modestly, especially near temples.",
    ],
  },
};

export const destinations: Destination[] = [jaipur, goa, manali, varanasi, ...extraDestinations];

export const experiences = [
  { label: "History", icon: "landmark", image: img("exp-history", 700, 900) },
  { label: "Mountains", icon: "mountain", image: img("exp-mountains", 700, 900) },
  { label: "Beaches", icon: "waves", image: img("exp-beaches", 700, 900) },
  { label: "Food", icon: "utensils", image: img("exp-food", 700, 900) },
  { label: "Culture", icon: "drama", image: img("exp-culture", 700, 900) },
  { label: "Wildlife", icon: "paw-print", image: img("exp-wildlife", 700, 900) },
] as const;

export function getDestination(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export function getAttraction(destSlug: string, attractionSlug: string) {
  const dest = getDestination(destSlug);
  const attraction = dest?.attractions.find((a) => a.slug === attractionSlug);
  return dest && attraction ? { dest, attraction } : undefined;
}
